//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Abuse_Type
    {
        public Abuse_Type()
        {
            this.CPR_Incident_Abuse_Types = new HashSet<Incident_Abuse_Type>();
            this.CPR_Unsuitability_Incedent = new HashSet<CPR_Unsuitability_Incedent>();
        }
    
        public int Abuse_Type_Id { get; set; }
        public string Description { get; set; }
        public string Source { get; set; }
        public string Definition { get; set; }
    
        public virtual ICollection<Incident_Abuse_Type> CPR_Incident_Abuse_Types { get; set; }
        public virtual ICollection<CPR_Unsuitability_Incedent> CPR_Unsuitability_Incedent { get; set; }
    }
}
