//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Abuse_Indicator
    {
        public Abuse_Indicator()
        {
            this.CPR_Incidents = new HashSet<CPR_Incident>();
            this.CPR_Unsuitability_Incident_Abuse_Indicator = new HashSet<CPR_Unsuitability_Incident_Abuse_Indicator>();
        }
    
        public int Abuse_Indicator_Id { get; set; }
        public string Description { get; set; }
        public string Source { get; set; }
        public string Definition { get; set; }
        public Nullable<int> Abuse_Type_Id { get; set; }
    
        public virtual ICollection<CPR_Incident> CPR_Incidents { get; set; }
        public virtual ICollection<CPR_Unsuitability_Incident_Abuse_Indicator> CPR_Unsuitability_Incident_Abuse_Indicator { get; set; }
    }
}
