//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACM_ExtensionOfAlternativeCareOrder
    {
        public ACM_ExtensionOfAlternativeCareOrder()
        {
            this.ACM_EvaluationRecommendationAndConclusion = new HashSet<ACM_EvaluationRecommendationAndConclusion>();
            this.ACM_FosterParentsDependants = new HashSet<ACM_FosterParentsDependants>();
            this.ACM_ProgressMadeByChildrenAndViewsOfFamilyMembers = new HashSet<ACM_ProgressMadeByChildrenAndViewsOfFamilyMembers>();
            this.ACM_SocialWorkerOrganisationDetails = new HashSet<ACM_SocialWorkerOrganisationDetails>();
            this.ACM_SupportAndServicesProvidedToTheParents = new HashSet<ACM_SupportAndServicesProvidedToTheParents>();
            this.ACM_TypesOfServicesAndSupport = new HashSet<ACM_TypesOfServicesAndSupport>();
        }
    
        public int ExtensionOfAlternativeCareOrder_Id { get; set; }
        public int CaseWorklist_Id { get; set; }
    
        public virtual ACM_CaseWorkList ACM_CaseWorkList { get; set; }
        public virtual ICollection<ACM_EvaluationRecommendationAndConclusion> ACM_EvaluationRecommendationAndConclusion { get; set; }
        public virtual ICollection<ACM_FosterParentsDependants> ACM_FosterParentsDependants { get; set; }
        public virtual ICollection<ACM_ProgressMadeByChildrenAndViewsOfFamilyMembers> ACM_ProgressMadeByChildrenAndViewsOfFamilyMembers { get; set; }
        public virtual ICollection<ACM_SocialWorkerOrganisationDetails> ACM_SocialWorkerOrganisationDetails { get; set; }
        public virtual ICollection<ACM_SupportAndServicesProvidedToTheParents> ACM_SupportAndServicesProvidedToTheParents { get; set; }
        public virtual ICollection<ACM_TypesOfServicesAndSupport> ACM_TypesOfServicesAndSupport { get; set; }
    }
}
