//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACM_AcknowledgementOfReceipt
    {
        public int Id { get; set; }
        public int AuthorityToRemove_Id { get; set; }
        public string Parent_Name { get; set; }
        public string Parent_Surname { get; set; }
        public string Parent_Place { get; set; }
        public Nullable<System.DateTime> Parent_Date { get; set; }
        public string Safecare_Name { get; set; }
        public string Safecare_Surname { get; set; }
        public string Safecare_Place { get; set; }
        public Nullable<System.DateTime> Safecare_Date { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int Placement_ID { get; set; }
    
        public virtual ACM_AuthorityToRemove ACM_AuthorityToRemove { get; set; }
        public virtual ACM_PlacementType ACM_PlacementType { get; set; }
    }
}
