//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACM_FamilyProfile
    {
        public ACM_FamilyProfile()
        {
            this.ACM_FamilyProfileMember = new HashSet<ACM_FamilyProfileMember>();
        }
    
        public int FamilyProfile_Id { get; set; }
        public int ChildrensCourtReport_Id { get; set; }
        public string PlaceOfBirth { get; set; }
        public string FamilyHistory { get; set; }
        public string Eductation { get; set; }
        public string EmploymentHistory { get; set; }
        public string ParentsRelationshipNature { get; set; }
        public string PsychologicalFactorsAndHealth { get; set; }
        public string PsychologicalFactors { get; set; }
        public string HousingType { get; set; }
        public string HousingOwnership { get; set; }
        public string HousingAdditionalInformation { get; set; }
        public string HousingSize { get; set; }
        public string Impression { get; set; }
        public string RCAffiliation { get; set; }
        public string RCRole { get; set; }
        public string RCParticipation { get; set; }
        public string RCAdditionalDetails { get; set; }
        public string SCCommunityActivities { get; set; }
        public string SCNormsandValues { get; set; }
        public string SCStatus { get; set; }
        public string SCAditionalDetails { get; set; }
        public string FAIncomeOfParents { get; set; }
        public string FAExpenditureOfParents { get; set; }
        public string FAAdditionalDetails { get; set; }
        public string CCPresentLivingCircumstanceNotWithBP { get; set; }
        public string CCPhysicalAndHealth { get; set; }
        public string CCPsychologicalFactors { get; set; }
        public string CCRelationsjhip { get; set; }
        public string CCSchooling { get; set; }
        public string AbandonedOrOrphanedChildren { get; set; }
        public string ChildrenWithSpecialNeeds { get; set; }
        public string ChildConcernedViews { get; set; }
    
        public virtual ACM_ChildrensCourtReport ACM_ChildrensCourtReport { get; set; }
        public virtual ICollection<ACM_FamilyProfileMember> ACM_FamilyProfileMember { get; set; }
    }
}
