//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACM_CopiesOfAuthority
    {
        public int Id { get; set; }
        public int AuthorityToRemove_Id { get; set; }
        public bool SupportingDocuments { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Organisation { get; set; }
        public string TelephoneNumber { get; set; }
        public string FacsimileNumber { get; set; }
        public string ReferenceNumber { get; set; }
    
        public virtual ACM_AuthorityToRemove ACM_AuthorityToRemove { get; set; }
    }
}
