//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACM_CourtOutcome
    {
        public int CourtOutcome_Id { get; set; }
        public Nullable<int> CourtProvince_Id { get; set; }
        public Nullable<int> Court_id { get; set; }
        public Nullable<int> District_Id { get; set; }
        public Nullable<System.DateTime> CourtDate { get; set; }
        public Nullable<int> CourtOutcomeStatus_Id { get; set; }
        public Nullable<int> TypeOfCourtOutcome_Id { get; set; }
        public string Comments { get; set; }
        public int CaseWorklist_Id { get; set; }
        public Nullable<int> AlternativeCareType_Id { get; set; }
        public Nullable<int> Cycc_Id { get; set; }
        public Nullable<int> FosterParentPerson_Id { get; set; }
        public Nullable<int> PlacementSection_Id { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string Duration { get; set; }
    
        public virtual ACM_CaseWorkList ACM_CaseWorkList { get; set; }
    }
}
