//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACM_ActuarialRiskAssessmentScoring
    {
        public int Id { get; set; }
        public int ActuarialRisk_Id { get; set; }
        public string A1 { get; set; }
        public string A2 { get; set; }
        public string A3 { get; set; }
        public string A4 { get; set; }
        public string A5 { get; set; }
        public bool A6_1 { get; set; }
        public bool A6_2 { get; set; }
        public bool A6_3 { get; set; }
        public bool A6_4 { get; set; }
        public bool A6_5 { get; set; }
        public string A7 { get; set; }
        public string A8 { get; set; }
        public string A9 { get; set; }
        public string A10 { get; set; }
        public string A11 { get; set; }
        public string A12 { get; set; }
        public string N1 { get; set; }
        public string N2 { get; set; }
        public string N3 { get; set; }
        public string N4 { get; set; }
        public string N5 { get; set; }
        public bool N6_1 { get; set; }
        public bool N6_2 { get; set; }
        public bool N6_3 { get; set; }
        public bool N6_4 { get; set; }
        public string N7 { get; set; }
        public string N8 { get; set; }
        public string E1 { get; set; }
        public string E2 { get; set; }
        public string E3 { get; set; }
        public string E4 { get; set; }
        public string E5 { get; set; }
        public string E6 { get; set; }
        public string E7 { get; set; }
    
        public virtual ACM_ActuarialRiskAssessment ACM_ActuarialRiskAssessment { get; set; }
    }
}
