//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACM_ConsentToSurgicalOperationByAChild
    {
        public ACM_ConsentToSurgicalOperationByAChild()
        {
            this.ACM_ParentsGuardiansAssentingToSurgicalOperation = new HashSet<ACM_ParentsGuardiansAssentingToSurgicalOperation>();
        }
    
        public int ConsentToSurgicalOperationByAChild_Id { get; set; }
        public Nullable<int> Client_Id { get; set; }
        public string SurgicalOperatorName { get; set; }
        public string SurgicalOperatorNumber { get; set; }
        public string SurgicalOperatorAddress { get; set; }
        public string SurgicalOperatorContactDetails { get; set; }
        public string NatureOfSurgicalOperation { get; set; }
        public string ApplicantContactDetails { get; set; }
        public string DetailsOfOtherInstitutionPerformingSurgicalOperation { get; set; }
        public string ParentAssentingToSurgicalOperation_Id { get; set; }
        public string GuardianAssentingToSurgicalOperation_ID { get; set; }
        public bool IsNatureOfProblem { get; set; }
        public string NatureOfProblemExplanation { get; set; }
        public bool IsTheMostSuitableSurgicalOperationInMyOpinion { get; set; }
        public string TheMostSuitableSurgicalOperationInMyOpinionExplanation { get; set; }
        public bool IsAnyRisksAssociatedWithTheSurgicalOperation { get; set; }
        public string AnyRisksAssociatedWithTheSurgicalOperationExplanation { get; set; }
        public bool IsBenefitsAssociatedWithSurgicalOperation { get; set; }
        public string BenefitsAssociatedWithSurgicalOperationExplanation { get; set; }
        public bool IsAnyAlternativeFormsOfTreatment { get; set; }
        public string AnyAlternativeFormsOfTreatmentExplanation { get; set; }
        public bool IsSocialImplicationsOfTreatment { get; set; }
        public string SocialImplicationsOfTreatmentExplanation { get; set; }
        public bool IsAnyOtherImplicationsPossibleConsequences { get; set; }
        public string AnyOtherImplicationsPossibleConsequencesExplanation { get; set; }
        public string PersonSeekingChildConsent { get; set; }
        public string TreatmentOrSurgicalOperationSocialImplications { get; set; }
        public string TreatmentOrSurgicalOperationDesignationOfPerSeeking { get; set; }
        public Nullable<System.DateTime> DateExplained { get; set; }
        public string TypeOfSurgicalOperation { get; set; }
        public Nullable<System.DateTime> ClientConsentDate { get; set; }
        public Nullable<System.DateTime> ParentOrGurdianConsentDate { get; set; }
        public int CaseWorklist_Id { get; set; }
    
        public virtual ACM_CaseWorkList ACM_CaseWorkList { get; set; }
        public virtual ICollection<ACM_ParentsGuardiansAssentingToSurgicalOperation> ACM_ParentsGuardiansAssentingToSurgicalOperation { get; set; }
    }
}
