//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACM_AraScoreRiskLevels
    {
        public int Id { get; set; }
        public int ActuarialRisk_Id { get; set; }
        public string AbuseScore { get; set; }
        public string NeglectScore { get; set; }
        public string ExploitationScore { get; set; }
        public string AbudeScoreRiskLevel { get; set; }
        public string NeglectScoreRiskLevel { get; set; }
        public string ExploitationScoreRiskLevel { get; set; }
    
        public virtual ACM_ActuarialRiskAssessment ACM_ActuarialRiskAssessment { get; set; }
    }
}
