//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACM_SummaryOfDevelopmentArea
    {
        public int SummaryOfDevelopmentArea_Id { get; set; }
        public int DevelopmentArea_Id { get; set; }
        public string DesiredOutcome { get; set; }
        public string WhatWillbeDone { get; set; }
        public string WhoWillDoThis { get; set; }
        public Nullable<System.DateTime> ByWhen { get; set; }
        public int CaseWorklist_Id { get; set; }
    }
}
