//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACM_SupportAndServiceRendered
    {
        public int SupportAndServiceRendered_Id { get; set; }
        public string ProgressSinceThePlacement { get; set; }
        public string CurrentCircumstances { get; set; }
        public string ViewsOfTheParent { get; set; }
        public string ContactBetweenCaregiverParentsAndTheConcernedChildren { get; set; }
        public int Transfer_Id { get; set; }
    
        public virtual ACM_Transfer ACM_Transfer { get; set; }
    }
}
