//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACM_TypeOfReportedSuspectedMaltreatment
    {
        public int Id { get; set; }
        public int Sasat_Id { get; set; }
        public string PhysicalAbuse { get; set; }
        public string SexualAbuse { get; set; }
        public string EmotionalAbuse { get; set; }
        public string ChildNeglect { get; set; }
        public string Exploitation { get; set; }
        public string Inappropriate { get; set; }
        public string Abandonment { get; set; }
        public string StreetChild { get; set; }
    
        public virtual ACM_SouthAfricanSafetyAssessmentTool ACM_SouthAfricanSafetyAssessmentTool { get; set; }
    }
}
