//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACM_Schedule
    {
        public int Schedule_Id { get; set; }
        public string PurposeOfAppointment { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public string Loaction { get; set; }
        public string Duration { get; set; }
        public int CaseWorkList_Id { get; set; }
        public bool IsCompleted { get; set; }
    
        public virtual ACM_CaseWorkList ACM_CaseWorkList { get; set; }
    }
}
