//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACM_AbscondmentDetails
    {
        public int AbscondmentDetails_Id { get; set; }
        public string Introduction { get; set; }
        public Nullable<int> CurrentPositioOfTheChildren { get; set; }
        public string ReasonsForAbscondment { get; set; }
        public string School_progress { get; set; }
        public string PresentAdjustmentInAlternativeCare { get; set; }
        public string RelationshipBetweenParentAndChild { get; set; }
        public string WorkAndFinances { get; set; }
        public string ReligiousAspects { get; set; }
        public string SocialAspects { get; set; }
        public string PhysicalAndPsychologicalAspects { get; set; }
        public Nullable<int> WasCareGiverInformedAboutApprehensionOfTheChild { get; set; }
        public string ReactionOfAttitudeOfTheCareGiver { get; set; }
        public string PlanOfAction { get; set; }
        public string Evaluation { get; set; }
        public string Recommendation { get; set; }
        public Nullable<int> SocialDeveloper_ID { get; set; }
        public Nullable<int> Organization_id { get; set; }
        public int Abscondment_id { get; set; }
    
        public virtual ACM_Abscondment ACM_Abscondment { get; set; }
    }
}
