//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACM_ViewsOfTheChild
    {
        public int ViewsOfTheChild_Id { get; set; }
        public Nullable<int> IsChildGivenOppornunityToExpressViews { get; set; }
        public Nullable<int> Client_id { get; set; }
        public string FosterParentName { get; set; }
        public int FosterCarePlan_Id { get; set; }
    
        public virtual ACM_FosterCarePlan ACM_FosterCarePlan { get; set; }
    }
}
