//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACM_EvaluationActivitiesResponsibilities
    {
        public int EvaluationActivitiesResponsibilities_Id { get; set; }
        public string NatureOfServiceToBeProvided { get; set; }
        public string Activities { get; set; }
        public Nullable<System.DateTime> PlanOfActionDate { get; set; }
        public string Responsibility { get; set; }
        public string MethodOfIntervention { get; set; }
        public Nullable<System.DateTime> EvaluationWhen { get; set; }
        public string EvaluationHow { get; set; }
        public int PlanOfAction_Id { get; set; }
    
        public virtual ACM_PlanOfAction ACM_PlanOfAction { get; set; }
    }
}
