//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACM_MotivationPlanofActionEvaluation
    {
        public int MotivationPlanofActionEvaluation_Id { get; set; }
        public string MotivationForTheTransfer { get; set; }
        public string PlanOfAction { get; set; }
        public string Evaluation { get; set; }
        public string Recommendation { get; set; }
        public int SocialWorker_Id { get; set; }
        public int Transfer_Id { get; set; }
    
        public virtual ACM_Transfer ACM_Transfer { get; set; }
    }
}
