//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACM_ChildAssessment
    {
        public ACM_ChildAssessment()
        {
            this.ACM_ChildrensCourtReport = new HashSet<ACM_ChildrensCourtReport>();
            this.ACM_InterventionPlanning = new HashSet<ACM_InterventionPlanning>();
            this.ACM_MedicalFactors = new HashSet<ACM_MedicalFactors>();
            this.ACM_SocialHistory = new HashSet<ACM_SocialHistory>();
            this.ACM_TentativeTreatment = new HashSet<ACM_TentativeTreatment>();
        }
    
        public int ChildAssessment_Id { get; set; }
        public string ReferalSource { get; set; }
        public string PresentingProblem { get; set; }
        public Nullable<int> TypeOfEngagement_Id { get; set; }
        public string NameOfPersonsParticipating { get; set; }
        public Nullable<int> RelationshipType_It { get; set; }
        public int CaseWorklist_Id { get; set; }
        public string OtherEngagementType { get; set; }
    
        public virtual ACM_CaseWorkList ACM_CaseWorkList { get; set; }
        public virtual ICollection<ACM_ChildrensCourtReport> ACM_ChildrensCourtReport { get; set; }
        public virtual ICollection<ACM_InterventionPlanning> ACM_InterventionPlanning { get; set; }
        public virtual ICollection<ACM_MedicalFactors> ACM_MedicalFactors { get; set; }
        public virtual ICollection<ACM_SocialHistory> ACM_SocialHistory { get; set; }
        public virtual ICollection<ACM_TentativeTreatment> ACM_TentativeTreatment { get; set; }
    }
}
