//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACM_ConsentApplyPassportOrRemovalFromSA
    {
        public ACM_ConsentApplyPassportOrRemovalFromSA()
        {
            this.ACM_DetailsOfChildParentsOrGuardian = new HashSet<ACM_DetailsOfChildParentsOrGuardian>();
            this.ACM_ParticularsOfTheChildInAlternativeCare = new HashSet<ACM_ParticularsOfTheChildInAlternativeCare>();
        }
    
        public int ConsentApplyPassportOrRemovalFromSA_Id { get; set; }
        public string ConsentToApplyForPassport { get; set; }
        public string ConsentToTravel { get; set; }
        public Nullable<System.DateTime> Consent_valid_from { get; set; }
        public Nullable<System.DateTime> Until { get; set; }
        public string GivenAt { get; set; }
        public string ON { get; set; }
        public string NameOfOfficer { get; set; }
        public string Level { get; set; }
        public int CareGiver_Id { get; set; }
        public int CaseWorklist_Id { get; set; }
    
        public virtual ICollection<ACM_DetailsOfChildParentsOrGuardian> ACM_DetailsOfChildParentsOrGuardian { get; set; }
        public virtual ICollection<ACM_ParticularsOfTheChildInAlternativeCare> ACM_ParticularsOfTheChildInAlternativeCare { get; set; }
    }
}
