//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACM_Recommendation
    {
        public int Recommendation_Id { get; set; }
        public int ChildernsCourtReport_Id { get; set; }
        public string Recommendation { get; set; }
        public string Motivation { get; set; }
    
        public virtual ACM_ChildrensCourtReport ACM_ChildrensCourtReport { get; set; }
    }
}
