//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACM_CarePlanReviewCaregiverDetails
    {
        public int CaregiverDetails_Id { get; set; }
        public Nullable<System.DateTime> DateOfLastReview { get; set; }
        public Nullable<System.DateTime> DateOfThisReview { get; set; }
        public int CaseWorklist_Id { get; set; }
    }
}
