//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACM_ReasonForRemoval
    {
        public int Id { get; set; }
        public Nullable<int> AuthorityToRemove_Id { get; set; }
        public bool Reason1 { get; set; }
        public bool Reason2 { get; set; }
        public bool Reason3 { get; set; }
        public bool Reason4 { get; set; }
        public bool Reason5 { get; set; }
        public bool Reason6 { get; set; }
        public bool Reason7 { get; set; }
        public bool Reason8 { get; set; }
        public bool Reason9 { get; set; }
        public bool Reason10 { get; set; }
        public bool Reason11 { get; set; }
        public bool Reason12 { get; set; }
        public bool Reason13 { get; set; }
        public bool Reason14 { get; set; }
    
        public virtual ACM_AuthorityToRemove ACM_AuthorityToRemove { get; set; }
    }
}
