//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACM_ACSSSocialWorkerDeclaration
    {
        public int ACSSSocialWorkerDeclaration_Id { get; set; }
        public string SocialWorker { get; set; }
        public Nullable<System.DateTime> DateSigned { get; set; }
        public string SignedAt { get; set; }
        public string DiscussedWith { get; set; }
        public Nullable<System.DateTime> DateDiscussed { get; set; }
        public int CaseWorklist_Id { get; set; }
    
        public virtual ACM_CaseWorkList ACM_CaseWorkList { get; set; }
    }
}
