//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACM_IDPMeetingAttendees
    {
        public int Attendee_Id { get; set; }
        public int Meeting_Id { get; set; }
        public bool DidAttend { get; set; }
    
        public virtual ACM_IDPMeeting ACM_IDPMeeting { get; set; }
    }
}
