//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACM_OfficialConductingTheRemoval
    {
        public int Id { get; set; }
        public int AuthorityToRemove_Id { get; set; }
        public bool isConductingTheRemoval { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Firstname { get; set; }
        public string Surname { get; set; }
        public string RankPosition { get; set; }
        public string IdentityNumber { get; set; }
        public string WorkAddress { get; set; }
        public string RegistrationNumber { get; set; }
        public string TelephoneNumber { get; set; }
        public string FacsimilyNumber { get; set; }
        public string EmailAddress { get; set; }
    
        public virtual ACM_AuthorityToRemove ACM_AuthorityToRemove { get; set; }
    }
}
