//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACM_FosterParentsDependants
    {
        public int FosterParentsDependants_Id { get; set; }
        public string Name { get; set; }
        public int Gender { get; set; }
        public string IDNumber { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public int Client_Id { get; set; }
        public int Person_Id { get; set; }
        public int ExtensionOfAlternativeCareOrder_Id { get; set; }
    
        public virtual ACM_ExtensionOfAlternativeCareOrder ACM_ExtensionOfAlternativeCareOrder { get; set; }
    }
}
