//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACM_ActuarialRiskAssessment
    {
        public ACM_ActuarialRiskAssessment()
        {
            this.ACM_AraScoreRiskLevels = new HashSet<ACM_AraScoreRiskLevels>();
            this.ACM_AraSourcesOfInformation = new HashSet<ACM_AraSourcesOfInformation>();
            this.ACM_ActuarialRiskAssessmentScoring = new HashSet<ACM_ActuarialRiskAssessmentScoring>();
        }
    
        public int Id { get; set; }
        public string Organization { get; set; }
        public string FamilyName { get; set; }
        public string FamilyAddress { get; set; }
        public Nullable<System.DateTime> DateOfAssessment { get; set; }
        public int Caseworklist_Id { get; set; }
    
        public virtual ICollection<ACM_AraScoreRiskLevels> ACM_AraScoreRiskLevels { get; set; }
        public virtual ICollection<ACM_AraSourcesOfInformation> ACM_AraSourcesOfInformation { get; set; }
        public virtual ICollection<ACM_ActuarialRiskAssessmentScoring> ACM_ActuarialRiskAssessmentScoring { get; set; }
    }
}
