//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACM_ManagementInspectionReport
    {
        public ACM_ManagementInspectionReport()
        {
            this.ACM_BoardOfManagement = new HashSet<ACM_BoardOfManagement>();
        }
    
        public int Id { get; set; }
        public int AlternativeCareDatabase_Id { get; set; }
        public string ConstitutionOfDomesticRules { get; set; }
        public string CompetencyOfManagement { get; set; }
        public bool hasSubCommitees { get; set; }
        public string SubCommiteeNature { get; set; }
        public string SubCommitteeNumberOfMembers { get; set; }
    
        public virtual ACM_AlternativeCareDatabase ACM_AlternativeCareDatabase { get; set; }
        public virtual ICollection<ACM_BoardOfManagement> ACM_BoardOfManagement { get; set; }
    }
}
