//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACM_Transfer
    {
        public ACM_Transfer()
        {
            this.ACM_ChildrenConcernedTransfer = new HashSet<ACM_ChildrenConcernedTransfer>();
            this.ACM_Identifyingparticulars = new HashSet<ACM_Identifyingparticulars>();
            this.ACM_IntroductionBackgroundTransfer = new HashSet<ACM_IntroductionBackgroundTransfer>();
            this.ACM_MotivationPlanofActionEvaluation = new HashSet<ACM_MotivationPlanofActionEvaluation>();
            this.ACM_PresentCircumstancesTransferReport = new HashSet<ACM_PresentCircumstancesTransferReport>();
            this.ACM_SiblingsORChildDetails = new HashSet<ACM_SiblingsORChildDetails>();
            this.ACM_SupportAndServiceRendered = new HashSet<ACM_SupportAndServiceRendered>();
        }
    
        public int Transfer_Id { get; set; }
        public int CaseWorklist_Id { get; set; }
    
        public virtual ACM_CaseWorkList ACM_CaseWorkList { get; set; }
        public virtual ICollection<ACM_ChildrenConcernedTransfer> ACM_ChildrenConcernedTransfer { get; set; }
        public virtual ICollection<ACM_Identifyingparticulars> ACM_Identifyingparticulars { get; set; }
        public virtual ICollection<ACM_IntroductionBackgroundTransfer> ACM_IntroductionBackgroundTransfer { get; set; }
        public virtual ICollection<ACM_MotivationPlanofActionEvaluation> ACM_MotivationPlanofActionEvaluation { get; set; }
        public virtual ICollection<ACM_PresentCircumstancesTransferReport> ACM_PresentCircumstancesTransferReport { get; set; }
        public virtual ICollection<ACM_SiblingsORChildDetails> ACM_SiblingsORChildDetails { get; set; }
        public virtual ICollection<ACM_SupportAndServiceRendered> ACM_SupportAndServiceRendered { get; set; }
    }
}
