//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACM_EvaluationRecommendationConclusion
    {
        public int Id { get; set; }
        public int ChildrensCourtReport_Id { get; set; }
        public string Evaluation { get; set; }
        public string Result { get; set; }
        public string Causes { get; set; }
        public string Recommendation { get; set; }
        public string Motivation { get; set; }
        public Nullable<int> Evaluation_id { get; set; }
    
        public virtual ACM_ChildrensCourtReport ACM_ChildrensCourtReport { get; set; }
    }
}
