//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACM_PlanOfAction
    {
        public ACM_PlanOfAction()
        {
            this.ACM_AgreementWithServiceBeneficiary = new HashSet<ACM_AgreementWithServiceBeneficiary>();
            this.ACM_EvaluationActivitiesResponsibilities = new HashSet<ACM_EvaluationActivitiesResponsibilities>();
        }
    
        public int PlanOfAction_Id { get; set; }
        public int CaseWorklist_Id { get; set; }
        public string NatureOfService { get; set; }
        public string Activities { get; set; }
        public Nullable<System.DateTime> PlanOfActionDate { get; set; }
        public string Responsibility { get; set; }
        public string MethodOfIntervention { get; set; }
        public Nullable<System.DateTime> EvaluationWhen { get; set; }
        public Nullable<System.DateTime> EvaluationHow { get; set; }
    
        public virtual ICollection<ACM_AgreementWithServiceBeneficiary> ACM_AgreementWithServiceBeneficiary { get; set; }
        public virtual ACM_CaseWorkList ACM_CaseWorkList { get; set; }
        public virtual ICollection<ACM_EvaluationActivitiesResponsibilities> ACM_EvaluationActivitiesResponsibilities { get; set; }
    }
}
