//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACM_IDPDevelopmentalAreaMastery
    {
        public int Mastery_Id { get; set; }
        public int IndividualDevelopmentPlan_Id { get; set; }
        public int SchoolLastAttended { get; set; }
        public string SchoolLastAttendedComment { get; set; }
        public int GradeChildWasIn { get; set; }
        public string GradeChildWasInComment { get; set; }
        public int WasChildPerformanceGood { get; set; }
        public string WasChildPerformanceGoodComment { get; set; }
        public int WasPositiveRelationships { get; set; }
        public string PositiveRelationshipsComment { get; set; }
        public int IsChildCurrentlyAttending { get; set; }
        public string IsChildCurrentlyAttendingComment { get; set; }
        public int GradeChildIsIn { get; set; }
        public string GradeChildIsInComment { get; set; }
        public int DoesChildAttendSchoolRegularly { get; set; }
        public string DoesChildAttendSchoolRegularlyComment { get; set; }
        public int DoesChildSubmitHomeWorkOnTime { get; set; }
        public string DoesChildSubmitHomeWorkOnTimeComment { get; set; }
        public int ChildLikeBeingInThatSchool { get; set; }
        public string ChildLikeBeingInThatSchoolComment { get; set; }
        public int DoesChildHaveLearningDisabilities { get; set; }
        public string DoesChildHaveLearningDisabilitiesComment { get; set; }
        public int IsAssessedByEducationalPsychologist { get; set; }
        public string IsAssessedByEducationalPsychologistComment { get; set; }
        public int IsChildOnMedication { get; set; }
        public string IsChildOnMedicationComment { get; set; }
        public string GeneralCompetency { get; set; }
        public string CaregiversAndvolunteersInvolvementInlearning { get; set; }
        public string SupportiveLearningEnvironments { get; set; }
        public string IsActivelyEngagedInLearningAndActivies { get; set; }
        public string IsEngagementWithRoleModelsAndMentors { get; set; }
        public string StrengthsAndResources { get; set; }
        public string NeedsAndconcerns { get; set; }
        public string ChangesWanted { get; set; }
        public string ActionsToEffectChange { get; set; }
    
        public virtual ACM_IndividualDevelopmentPlan ACM_IndividualDevelopmentPlan { get; set; }
    }
}
