//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACM_InterventionEvaluationReport
    {
        public int InterventionEvaluationReport_Id { get; set; }
        public Nullable<System.DateTime> DateOfReferral { get; set; }
        public string PresentingProblem { get; set; }
        public int NumberOfSessionsConducted { get; set; }
        public string PeriodOfServiceDelivery { get; set; }
        public string MainGoalsOfIntervention { get; set; }
        public string MainInterventionActivities { get; set; }
        public string ClientsExperienceOfChange { get; set; }
        public string Clientperception { get; set; }
        public string ClientAssessmentofChange { get; set; }
        public string YourPerceptionOfCurrentSituation { get; set; }
        public string FurtherPlanOfAction { get; set; }
        public int Practitione_Id { get; set; }
        public int CaseWorklist_Id { get; set; }
        public string YourAssessmentOfChange { get; set; }
        public int Section_Id { get; set; }
    
        public virtual ACM_CaseWorkList ACM_CaseWorkList { get; set; }
    }
}
