//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACM_IndividualDevelopmentPlan
    {
        public ACM_IndividualDevelopmentPlan()
        {
            this.ACM_IDPChildrenDetails = new HashSet<ACM_IDPChildrenDetails>();
            this.ACM_IDPMeeting = new HashSet<ACM_IDPMeeting>();
            this.ACM_IDPOtherSignificantPeople = new HashSet<ACM_IDPOtherSignificantPeople>();
            this.ACM_IDPParentsDetails = new HashSet<ACM_IDPParentsDetails>();
            this.ACM_IDPDevelopmentalAreaGenerosity = new HashSet<ACM_IDPDevelopmentalAreaGenerosity>();
            this.ACM_IDPDevelopmentalAreaIndependence = new HashSet<ACM_IDPDevelopmentalAreaIndependence>();
            this.ACM_IDPDevelopmentalAreaMastery = new HashSet<ACM_IDPDevelopmentalAreaMastery>();
            this.ACM_IDPDevelopmentalAreaBeloning = new HashSet<ACM_IDPDevelopmentalAreaBeloning>();
            this.ACM_IDPWellbeing = new HashSet<ACM_IDPWellbeing>();
            this.ACM_IDPConsultedPeople = new HashSet<ACM_IDPConsultedPeople>();
        }
    
        public int IndividualDevelopmentPlan_Id { get; set; }
        public Nullable<System.DateTime> DateOfAssessment { get; set; }
        public Nullable<System.DateTime> DateAssessmentReportCompleted { get; set; }
        public Nullable<int> Employer_Id { get; set; }
        public int CaseWorklist_Id { get; set; }
    
        public virtual ACM_CaseWorkList ACM_CaseWorkList { get; set; }
        public virtual ICollection<ACM_IDPChildrenDetails> ACM_IDPChildrenDetails { get; set; }
        public virtual ICollection<ACM_IDPMeeting> ACM_IDPMeeting { get; set; }
        public virtual ICollection<ACM_IDPOtherSignificantPeople> ACM_IDPOtherSignificantPeople { get; set; }
        public virtual ICollection<ACM_IDPParentsDetails> ACM_IDPParentsDetails { get; set; }
        public virtual ICollection<ACM_IDPDevelopmentalAreaGenerosity> ACM_IDPDevelopmentalAreaGenerosity { get; set; }
        public virtual ICollection<ACM_IDPDevelopmentalAreaIndependence> ACM_IDPDevelopmentalAreaIndependence { get; set; }
        public virtual ICollection<ACM_IDPDevelopmentalAreaMastery> ACM_IDPDevelopmentalAreaMastery { get; set; }
        public virtual ICollection<ACM_IDPDevelopmentalAreaBeloning> ACM_IDPDevelopmentalAreaBeloning { get; set; }
        public virtual ICollection<ACM_IDPWellbeing> ACM_IDPWellbeing { get; set; }
        public virtual ICollection<ACM_IDPConsultedPeople> ACM_IDPConsultedPeople { get; set; }
    }
}
