//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACM_AgreementWithServiceBeneficiary
    {
        public int AgreementWithServiceBeneficiary_Id { get; set; }
        public Nullable<int> SocialWorker_Id { get; set; }
        public string SignedAt { get; set; }
        public Nullable<System.DateTime> DateSigned { get; set; }
        public int PlanOfAction_Id { get; set; }
    
        public virtual ACM_PlanOfAction ACM_PlanOfAction { get; set; }
    }
}
