//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACM_MedicalFactors
    {
        public int MedicalFactors_Id { get; set; }
        public int ChildAssessment_Id { get; set; }
        public string HidtoryAndDevelopment { get; set; }
        public string Implications { get; set; }
        public string DisclosureToSignificantOthers { get; set; }
        public string CopingMechanisms { get; set; }
        public string MotivationForMedicalTreatment { get; set; }
        public bool IsProblemIssueNeeds { get; set; }
        public bool IsPersonAndSituation { get; set; }
        public bool IsPersonIssueSituation { get; set; }
        public string NatureOfProblem { get; set; }
        public string ContributingFactors { get; set; }
        public string DurationSeverityAndUrgencyOfResponse { get; set; }
        public string PersonalFamilyStrengths { get; set; }
        public string SituationalStrengths { get; set; }
        public string RiskAssessment { get; set; }
        public string AssessmentOutcome { get; set; }
        public string Assumptions { get; set; }
        public string EvaluationBySW { get; set; }
    
        public virtual ACM_ChildAssessment ACM_ChildAssessment { get; set; }
    }
}
