//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACM_InterviewProcessNote
    {
        public ACM_InterviewProcessNote()
        {
            this.ACM_InterviewedPersons = new HashSet<ACM_InterviewedPersons>();
        }
    
        public int ProcessNote_Id { get; set; }
        public int CaseWorklist_Id { get; set; }
        public Nullable<System.DateTime> ProcessNoteDateOfInterview { get; set; }
        public Nullable<int> InterviewType_Id { get; set; }
        public string PurposeOfInterview { get; set; }
        public string Process { get; set; }
        public string Evaluation { get; set; }
        public string PlanOfAction { get; set; }
        public Nullable<int> SocialWorker_Id { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ACM_Interview_Type ACM_Interview_Type { get; set; }
        public virtual ICollection<ACM_InterviewedPersons> ACM_InterviewedPersons { get; set; }
        public virtual Social_Worker apl_Social_Worker { get; set; }
    }
}
