//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACM_SafetyThreats
    {
        public int Id { get; set; }
        public int Sasat_Id { get; set; }
        public string ParentCaregiverCausedSeriousHarm { get; set; }
        public bool IsSeriousInjury { get; set; }
        public bool IsCaregiverExpressesFears { get; set; }
        public bool IsLackOfSelfControl { get; set; }
        public bool IsThreatensToCauseHarm { get; set; }
        public bool IsUsesExcessiveDiscipline { get; set; }
        public bool IsDrugExposedInfant { get; set; }
        public bool IsDomesticAnimalAbuse { get; set; }
        public string DoesNotProtectChild { get; set; }
        public string ExplanationForTheInjury { get; set; }
        public string FailsToMeetNeeds { get; set; }
        public string CurrentlyAbusesSubstances { get; set; }
        public string PredominantlyNegativeWay { get; set; }
        public string DevelopmentalStatus { get; set; }
        public string DistortedPerception { get; set; }
        public string CurrentCircumstance { get; set; }
        public string ChildSexualAbuse { get; set; }
        public string AccessRefused { get; set; }
        public string HazardouzLivingConditions { get; set; }
        public string ThreatToBeAddressed { get; set; }
        public string ViolenceExists { get; set; }
        public string FearfulOfParent { get; set; }
        public string Other { get; set; }
        public string OtherDescription { get; set; }
    
        public virtual ACM_SouthAfricanSafetyAssessmentTool ACM_SouthAfricanSafetyAssessmentTool { get; set; }
    }
}
