//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACM_MedicalParticulars
    {
        public int MedicalParticulars_Id { get; set; }
        public string Height { get; set; }
        public string Weight { get; set; }
        public string Lungs { get; set; }
        public string Heart { get; set; }
        public string Teeth { get; set; }
        public string Sight { get; set; }
        public string Hearing { get; set; }
        public string Speech { get; set; }
        public string Orthopedic { get; set; }
        public string Neurological { get; set; }
        public string Intellectual { get; set; }
        public Nullable<bool> IsPresenceOfAnyDisease { get; set; }
        public Nullable<bool> IsPresenceOfAnyDiseaseInfections { get; set; }
        public Nullable<bool> IsPresenceOfAnyInjury { get; set; }
        public string IfIsPresenceOfDiseaseORInfectionsORInjurySpecify { get; set; }
        public Nullable<bool> IsPhysicalDevelopmentAccordingToAge { get; set; }
        public string IfPhysicalDevelopmentAbnormalSpecify { get; set; }
        public Nullable<bool> IsNutrition { get; set; }
        public string IfNutritionDeficientSpecify { get; set; }
        public int CaseWorklist_Id { get; set; }
    
        public virtual ACM_CaseWorkList ACM_CaseWorkList { get; set; }
    }
}
