//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACM_FosterCarePlan
    {
        public ACM_FosterCarePlan()
        {
            this.ACM_ChildInFosterCareResponsibilitiesAndRights = new HashSet<ACM_ChildInFosterCareResponsibilitiesAndRights>();
            this.ACM_SocialWorkerDetailsOrderOfCourt = new HashSet<ACM_SocialWorkerDetailsOrderOfCourt>();
            this.ACM_ViewsOfTheChild = new HashSet<ACM_ViewsOfTheChild>();
        }
    
        public int FosterCarePlan_Id { get; set; }
        public int CaseWorklist_Id { get; set; }
        public string DayToDayCareChildDetails { get; set; }
        public string MattersParentsContentRequired { get; set; }
        public string AgreedContactDetails { get; set; }
        public string ParticularsOfReunificationServices { get; set; }
        public string FinancialContributionsToTheChild { get; set; }
        public string ParticularsOfSupervisionAndMonitoringServices { get; set; }
        public string AnyAdditionalInformation { get; set; }
    
        public virtual ACM_CaseWorkList ACM_CaseWorkList { get; set; }
        public virtual ICollection<ACM_ChildInFosterCareResponsibilitiesAndRights> ACM_ChildInFosterCareResponsibilitiesAndRights { get; set; }
        public virtual ICollection<ACM_SocialWorkerDetailsOrderOfCourt> ACM_SocialWorkerDetailsOrderOfCourt { get; set; }
        public virtual ICollection<ACM_ViewsOfTheChild> ACM_ViewsOfTheChild { get; set; }
    }
}
