//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACM_FactorsResultingToInvestigation
    {
        public int Factors_Id { get; set; }
        public int ChildrensCourtReport_Id { get; set; }
        public string Events { get; set; }
        public string PreviousIntervention { get; set; }
        public string EvidenceAndFacts { get; set; }
        public string MedicalEvidence { get; set; }
    
        public virtual ACM_ChildrensCourtReport ACM_ChildrensCourtReport { get; set; }
    }
}
