//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACM_DischargeFromAlternativeCare
    {
        public int DischargeFromAlternativeCare_Id { get; set; }
        public string Introduction { get; set; }
        public string ServicesRendered { get; set; }
        public string CurrentSituation { get; set; }
        public string Evaluation { get; set; }
        public string Recommandation { get; set; }
        public Nullable<int> Client_id { get; set; }
        public Nullable<int> SocialWoker_id { get; set; }
        public int CaseWorklist_Id { get; set; }
        public Nullable<System.DateTime> DateReportCompiled { get; set; }
    
        public virtual ACM_CaseWorkList ACM_CaseWorkList { get; set; }
    }
}
