//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACM_CaseWorkList
    {
        public ACM_CaseWorkList()
        {
            this.ACM_ChildAssessment = new HashSet<ACM_ChildAssessment>();
            this.ACM_IndividualDevelopmentPlan = new HashSet<ACM_IndividualDevelopmentPlan>();
            this.ACM_Investigation = new HashSet<ACM_Investigation>();
            this.ACM_Schedule = new HashSet<ACM_Schedule>();
            this.ACM_Abscondment = new HashSet<ACM_Abscondment>();
            this.ACM_AbuseDetails = new HashSet<ACM_AbuseDetails>();
            this.ACM_ACSSCareGiverDeclaration = new HashSet<ACM_ACSSCareGiverDeclaration>();
            this.ACM_ACSSSocialWorkerDeclaration = new HashSet<ACM_ACSSSocialWorkerDeclaration>();
            this.ACM_ApplicationForMinisterConsent = new HashSet<ACM_ApplicationForMinisterConsent>();
            this.ACM_AproovalToRemainInTheCareOfCYCC = new HashSet<ACM_AproovalToRemainInTheCareOfCYCC>();
            this.ACM_CarePlan = new HashSet<ACM_CarePlan>();
            this.ACM_DischargeFromAlternativeCare = new HashSet<ACM_DischargeFromAlternativeCare>();
            this.ACM_ChildDetailsRemovalAlreadyInAlternativeCare = new HashSet<ACM_ChildDetailsRemovalAlreadyInAlternativeCare>();
            this.ACM_ConsentToSurgicalOperationByAChild = new HashSet<ACM_ConsentToSurgicalOperationByAChild>();
            this.ACM_DeathDetails = new HashSet<ACM_DeathDetails>();
            this.ACM_ExtensionOfAlternativeCareOrder = new HashSet<ACM_ExtensionOfAlternativeCareOrder>();
            this.ACM_FosterCarePlan = new HashSet<ACM_FosterCarePlan>();
            this.ACM_InterventionEvaluationReport = new HashSet<ACM_InterventionEvaluationReport>();
            this.ACM_LeaveOfAbsence = new HashSet<ACM_LeaveOfAbsence>();
            this.ACM_MedicalParticulars = new HashSet<ACM_MedicalParticulars>();
            this.ACM_PlacementSupervisionAndAfterCare = new HashSet<ACM_PlacementSupervisionAndAfterCare>();
            this.ACM_PlanOfAction = new HashSet<ACM_PlanOfAction>();
            this.ACM_SeriousInjuryDetails = new HashSet<ACM_SeriousInjuryDetails>();
            this.ACM_Transfer = new HashSet<ACM_Transfer>();
            this.ACM_CourtOutcome = new HashSet<ACM_CourtOutcome>();
        }
    
        public int CaseWoklist_Id { get; set; }
        public Nullable<int> RecordStatus_Id { get; set; }
        public string CourtOrderRefNumber { get; set; }
        public Nullable<System.DateTime> CourtOrderExpiryDate { get; set; }
        public Nullable<System.DateTime> CourtOrderExtentionDate { get; set; }
        public Nullable<int> CourtOrderStatus { get; set; }
        public int Intake_Assessment_Id { get; set; }
        public string Reference_Number { get; set; }
        public Nullable<int> User_Id { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual Intake_Assessment int_Intake_Assessment { get; set; }
        public virtual ICollection<ACM_ChildAssessment> ACM_ChildAssessment { get; set; }
        public virtual ICollection<ACM_IndividualDevelopmentPlan> ACM_IndividualDevelopmentPlan { get; set; }
        public virtual ICollection<ACM_Investigation> ACM_Investigation { get; set; }
        public virtual ICollection<ACM_Schedule> ACM_Schedule { get; set; }
        public virtual apl_Record_Status apl_Record_Status { get; set; }
        public virtual ICollection<ACM_Abscondment> ACM_Abscondment { get; set; }
        public virtual ICollection<ACM_AbuseDetails> ACM_AbuseDetails { get; set; }
        public virtual ICollection<ACM_ACSSCareGiverDeclaration> ACM_ACSSCareGiverDeclaration { get; set; }
        public virtual ICollection<ACM_ACSSSocialWorkerDeclaration> ACM_ACSSSocialWorkerDeclaration { get; set; }
        public virtual ICollection<ACM_ApplicationForMinisterConsent> ACM_ApplicationForMinisterConsent { get; set; }
        public virtual ICollection<ACM_AproovalToRemainInTheCareOfCYCC> ACM_AproovalToRemainInTheCareOfCYCC { get; set; }
        public virtual ICollection<ACM_CarePlan> ACM_CarePlan { get; set; }
        public virtual ICollection<ACM_DischargeFromAlternativeCare> ACM_DischargeFromAlternativeCare { get; set; }
        public virtual ICollection<ACM_ChildDetailsRemovalAlreadyInAlternativeCare> ACM_ChildDetailsRemovalAlreadyInAlternativeCare { get; set; }
        public virtual ICollection<ACM_ConsentToSurgicalOperationByAChild> ACM_ConsentToSurgicalOperationByAChild { get; set; }
        public virtual ICollection<ACM_DeathDetails> ACM_DeathDetails { get; set; }
        public virtual ICollection<ACM_ExtensionOfAlternativeCareOrder> ACM_ExtensionOfAlternativeCareOrder { get; set; }
        public virtual ICollection<ACM_FosterCarePlan> ACM_FosterCarePlan { get; set; }
        public virtual ICollection<ACM_InterventionEvaluationReport> ACM_InterventionEvaluationReport { get; set; }
        public virtual ICollection<ACM_LeaveOfAbsence> ACM_LeaveOfAbsence { get; set; }
        public virtual ICollection<ACM_MedicalParticulars> ACM_MedicalParticulars { get; set; }
        public virtual ICollection<ACM_PlacementSupervisionAndAfterCare> ACM_PlacementSupervisionAndAfterCare { get; set; }
        public virtual ICollection<ACM_PlanOfAction> ACM_PlanOfAction { get; set; }
        public virtual ICollection<ACM_SeriousInjuryDetails> ACM_SeriousInjuryDetails { get; set; }
        public virtual ICollection<ACM_Transfer> ACM_Transfer { get; set; }
        public virtual ICollection<ACM_CourtOutcome> ACM_CourtOutcome { get; set; }
    }
}
