//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACM_IDPDevelopmentalAreaIndependence
    {
        public int Independence_Id { get; set; }
        public int IndividualDevelopmentPlan_Id { get; set; }
        public string PlanningAndDecisionMaking { get; set; }
        public string PersonalPower { get; set; }
        public string ResponsibilityForSelf { get; set; }
        public string EngagesInActivitiesPrepareFuture { get; set; }
        public string PositiveViewOpersonalFuture { get; set; }
        public string StrengthAndResources { get; set; }
        public string NeedsAndConcerns { get; set; }
        public string ChangesWanted { get; set; }
        public string ActionsToEffectChange { get; set; }
    
        public virtual ACM_IndividualDevelopmentPlan ACM_IndividualDevelopmentPlan { get; set; }
    }
}
