//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACM_InterventionPlanning
    {
        public int InterventionPlanning_Id { get; set; }
        public int ChildAssesment_Id { get; set; }
        public string FamilyExpectation { get; set; }
        public string ActionPlan { get; set; }
        public string ClientTasks { get; set; }
        public string SocialWorkerTasks { get; set; }
        public string PlansToEvaluate { get; set; }
        public Nullable<int> SocialWorker_Id { get; set; }
        public string SocialWorkerPracticeNumber { get; set; }
        public Nullable<int> Supervisors_Id { get; set; }
        public string SupervisorsPracticeNumber { get; set; }
    
        public virtual ACM_ChildAssessment ACM_ChildAssessment { get; set; }
    }
}
