//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACM_ChildDetailsRemovalAlreadyInAlternativeCare
    {
        public int ChildDetailsRemovalAlreadyInAlternativeCare_Id { get; set; }
        public Nullable<int> Client_id { get; set; }
        public Nullable<int> TypeOfPlacement { get; set; }
        public string Address { get; set; }
        public Nullable<int> CourtOrderType { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<System.DateTime> WithEffectFrom { get; set; }
        public string GivenAt { get; set; }
        public Nullable<System.DateTime> OnThisDate { get; set; }
        public string Level { get; set; }
        public Nullable<int> TemporarySafeCare { get; set; }
        public Nullable<System.DateTime> From { get; set; }
        public int CaseWorklist_Id { get; set; }
    
        public virtual ACM_CaseWorkList ACM_CaseWorkList { get; set; }
    }
}
