//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACM_IDPChildrenDetails
    {
        public int ChildDetails_Id { get; set; }
        public string FileNumber { get; set; }
        public Nullable<int> Placement_Id { get; set; }
        public Nullable<System.DateTime> DatePlacedInAlternativeCare { get; set; }
        public string NameOfCentreManager { get; set; }
        public string OtherPlacement { get; set; }
        public int IndividualDevelopmentPlan_Id { get; set; }
        public Nullable<int> Person_Id { get; set; }
    
        public virtual ACM_IndividualDevelopmentPlan ACM_IndividualDevelopmentPlan { get; set; }
    }
}
