//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACM_SafetyDecision
    {
        public int Id { get; set; }
        public int Sasat_Id { get; set; }
        public string OutOfControl { get; set; }
        public string SituationIsSpecific { get; set; }
        public string SevereHarm { get; set; }
        public string ThreatToSafety { get; set; }
        public string EmployProtectiveCapacities { get; set; }
        public string AnalysedToSupport { get; set; }
        public bool NoSafetyThreats { get; set; }
        public bool ThreatsArePresent { get; set; }
        public bool PresenceOfThreatsWithVulnerableChild { get; set; }
        public bool OneOrMoreSafetyThreats { get; set; }
        public string AllChildrenInvolvedAssessed { get; set; }
    
        public virtual ACM_SouthAfricanSafetyAssessmentTool ACM_SouthAfricanSafetyAssessmentTool { get; set; }
    }
}
