//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACM_ApplicationForMinisterConsent
    {
        public int ApplicationForMinisterConsent_Id { get; set; }
        public Nullable<int> Client_Id { get; set; }
        public string ApplicantFirstName { get; set; }
        public string ApplicantLastName { get; set; }
        public Nullable<System.DateTime> ApplicantDateOfBirth { get; set; }
        public string ApplicantIdentityNumber { get; set; }
        public string ApplicantPassportNumber { get; set; }
        public string ApplicantContactDetails { get; set; }
        public string ApplicantRelationShipToChild { get; set; }
        public string EnvisagedDescriptionOfMedicalTreatment { get; set; }
        public bool IsUnreasonablyRefusingConsent { get; set; }
        public string UnreasonablyRefusingConsentMotivation { get; set; }
        public bool IsIncapableOfGivingÇonsent { get; set; }
        public string IncapableOfGivingÇonsentMotivation { get; set; }
        public bool IsParentNotTraceable { get; set; }
        public string StepsTakenToTraceParents { get; set; }
        public bool IsChildUnreasonableRefusingToGiveConsent { get; set; }
        public string ChildUnreasonableRefusingToGiveConsentComment { get; set; }
        public string ConsentOrRefusalFirstName { get; set; }
        public string ConsentOrRefusalLastName { get; set; }
        public Nullable<System.DateTime> ConsentOrRefusalDate { get; set; }
        public string ConsentOrRefusalDesignation { get; set; }
        public Nullable<bool> ConsentStatus { get; set; }
        public int CaseWorklist_Id { get; set; }
    
        public virtual ACM_CaseWorkList ACM_CaseWorkList { get; set; }
    }
}
