//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACM_SocialWorkerDetailsOrderOfCourt
    {
        public int SocialWorkerDetailsOrderOfCourt_Id { get; set; }
        public Nullable<int> SocialWorker_Id { get; set; }
        public string ChildProtectionAgencyName { get; set; }
        public string PresidingOfficerChildrenCourt { get; set; }
        public string ChildrenCourtLocation { get; set; }
        public int FosterCarePlan_Id { get; set; }
    
        public virtual ACM_FosterCarePlan ACM_FosterCarePlan { get; set; }
    }
}
