//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACM_ChildrenConcerned
    {
        public int ID { get; set; }
        public int ChildrensCourtReport_Id { get; set; }
        public string PresentLivingCircumstances { get; set; }
        public string PhysicalFactorsAndHealth { get; set; }
        public string PsychologicalFactors { get; set; }
        public string RelationshipsWithParents { get; set; }
        public string Schooling_Abilities { get; set; }
        public string Schooling_Problems { get; set; }
        public string Schooling_Difficulties { get; set; }
        public string Schooling_Achievements { get; set; }
    
        public virtual ACM_ChildrensCourtReport ACM_ChildrensCourtReport { get; set; }
    }
}
