//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACM_ACSSCareGiverDeclaration
    {
        public int ACSSCareGiverDeclaration_Id { get; set; }
        public string AlternativeAareGivers { get; set; }
        public bool IsWillingAndAbleToCareForTheYoungPerson { get; set; }
        public bool IsContentsOfTheReportWereDiscussedWithMe { get; set; }
        public bool IsEntitledToParticipateInProceedingsOfTheReview { get; set; }
        public bool IsExtensionOfTheOrderForAfurtherPeriodRecommended { get; set; }
        public bool IsSatisfiedWithTheRecommendationOfTheSocialWorker { get; set; }
        public string SignedAt { get; set; }
        public Nullable<System.DateTime> DateSigned { get; set; }
        public string ClusterFosterCareSchemeManager { get; set; }
        public string CYCCManager { get; set; }
        public int CaseWorklist_Id { get; set; }
    
        public virtual ACM_CaseWorkList ACM_CaseWorkList { get; set; }
    }
}
