//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACM_RecommendedAssistChildFamily
    {
        public int ChildFamily_Id { get; set; }
        public int ChildrensCourtReport_Id { get; set; }
        public bool IsCouncelling { get; set; }
        public string Councelling { get; set; }
        public bool IsMediation { get; set; }
        public string Mediation { get; set; }
        public bool IsPreevention { get; set; }
        public string Prevention { get; set; }
        public bool IsReconstruction { get; set; }
        public string Reconstruction { get; set; }
        public bool IsBehavior { get; set; }
        public string Behavior { get; set; }
        public bool IsProblemSolving { get; set; }
        public string ProblemSolving { get; set; }
        public bool IsReferral { get; set; }
        public string Referral { get; set; }
        public bool IsOther { get; set; }
        public string Other { get; set; }
    
        public virtual ACM_ChildrensCourtReport ACM_ChildrensCourtReport { get; set; }
    }
}
