//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACM_AlternativeCareDatabase
    {
        public ACM_AlternativeCareDatabase()
        {
            this.ACM_ManagementInspectionReport = new HashSet<ACM_ManagementInspectionReport>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> DateOfInspection { get; set; }
        public string PurposeOfInspection { get; set; }
        public string NameOfChildAndYouthCentre { get; set; }
        public string PhysicalAddress { get; set; }
        public string PostalAddress { get; set; }
        public string ManagerName { get; set; }
        public string ManagerPhysicalAddress { get; set; }
        public string TelephoneNumber { get; set; }
        public string CellphoneNumber { get; set; }
        public string Email { get; set; }
        public string AccreditationReferenceNumber { get; set; }
    
        public virtual ICollection<ACM_ManagementInspectionReport> ACM_ManagementInspectionReport { get; set; }
    }
}
