//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACM_SouthAfricanSafetyAssessmentTool
    {
        public ACM_SouthAfricanSafetyAssessmentTool()
        {
            this.ACM_ChildVulnerability = new HashSet<ACM_ChildVulnerability>();
            this.ACM_ParentCaregiversAssessed = new HashSet<ACM_ParentCaregiversAssessed>();
            this.ACM_ProtectiveCapacities = new HashSet<ACM_ProtectiveCapacities>();
            this.ACM_SafetyDecision = new HashSet<ACM_SafetyDecision>();
            this.ACM_SafetyInterventions = new HashSet<ACM_SafetyInterventions>();
            this.ACM_SafetyThreats = new HashSet<ACM_SafetyThreats>();
            this.ACM_TypeOfReportedSuspectedMaltreatment = new HashSet<ACM_TypeOfReportedSuspectedMaltreatment>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Organization_Id { get; set; }
        public Nullable<System.DateTime> DateOfAssessment { get; set; }
        public string FamilyAddress { get; set; }
        public string ReferalName { get; set; }
        public string FamilyName { get; set; }
        public Nullable<int> Client_Id { get; set; }
        public int Caseworklist_Id { get; set; }
    
        public virtual ICollection<ACM_ChildVulnerability> ACM_ChildVulnerability { get; set; }
        public virtual ICollection<ACM_ParentCaregiversAssessed> ACM_ParentCaregiversAssessed { get; set; }
        public virtual ICollection<ACM_ProtectiveCapacities> ACM_ProtectiveCapacities { get; set; }
        public virtual ICollection<ACM_SafetyDecision> ACM_SafetyDecision { get; set; }
        public virtual ICollection<ACM_SafetyInterventions> ACM_SafetyInterventions { get; set; }
        public virtual ICollection<ACM_SafetyThreats> ACM_SafetyThreats { get; set; }
        public virtual ICollection<ACM_TypeOfReportedSuspectedMaltreatment> ACM_TypeOfReportedSuspectedMaltreatment { get; set; }
    }
}
