//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACM_ChildrensCourtReport
    {
        public ACM_ChildrensCourtReport()
        {
            this.ACM_BiologicalParents = new HashSet<ACM_BiologicalParents>();
            this.ACM_Caregivers = new HashSet<ACM_Caregivers>();
            this.ACM_Evaluation = new HashSet<ACM_Evaluation>();
            this.ACM_FactorsResultingToInvestigation = new HashSet<ACM_FactorsResultingToInvestigation>();
            this.ACM_FamilyProfile = new HashSet<ACM_FamilyProfile>();
            this.ACM_IdentifyingChildDetails = new HashSet<ACM_IdentifyingChildDetails>();
            this.ACM_InformationSources = new HashSet<ACM_InformationSources>();
            this.ACM_MeasuresToAssistFamily = new HashSet<ACM_MeasuresToAssistFamily>();
            this.ACM_OtherPersons = new HashSet<ACM_OtherPerson>();
            this.ACM_PermanencyPlan = new HashSet<ACM_PermanencyPlan>();
            this.ACM_PrivateFamilyArrangements = new HashSet<ACM_PrivateFamilyArrangements>();
            this.ACM_Recommendation = new HashSet<ACM_Recommendation>();
            this.ACM_RecommendedAssistChild = new HashSet<ACM_RecommendedAssistChild>();
            this.ACM_RecommendedAssistChildFamily = new HashSet<ACM_RecommendedAssistChildFamily>();
            this.ACM_Siblings = new HashSet<ACM_Siblings>();
            this.ACM_WrittenRequest = new HashSet<ACM_WrittenRequest>();
            this.ACM_ChildrenConcerned = new HashSet<ACM_ChildrenConcerned>();
            this.ACM_SpecialCurcumstances = new HashSet<ACM_SpecialCurcumstances>();
            this.ACM_ViewsOfChildConcerned = new HashSet<ACM_ViewsOfChildConcerned>();
            this.ACM_EvaluationRecommendationConclusion = new HashSet<ACM_EvaluationRecommendationConclusion>();
        }
    
        public int ChildrensCourtReport_Id { get; set; }
        public int ChildAssesment_Id { get; set; }
        public string FileNumber { get; set; }
        public string DepartmentOf { get; set; }
        public string CourtFileNumber { get; set; }
        public string Introduction { get; set; }
        public Nullable<int> ReportByUser_Id { get; set; }
    
        public virtual ICollection<ACM_BiologicalParents> ACM_BiologicalParents { get; set; }
        public virtual ACM_ChildAssessment ACM_ChildAssessment { get; set; }
        public virtual ICollection<ACM_Caregivers> ACM_Caregivers { get; set; }
        public virtual User apl_User { get; set; }
        public virtual ICollection<ACM_Evaluation> ACM_Evaluation { get; set; }
        public virtual ICollection<ACM_FactorsResultingToInvestigation> ACM_FactorsResultingToInvestigation { get; set; }
        public virtual ICollection<ACM_FamilyProfile> ACM_FamilyProfile { get; set; }
        public virtual ICollection<ACM_IdentifyingChildDetails> ACM_IdentifyingChildDetails { get; set; }
        public virtual ICollection<ACM_InformationSources> ACM_InformationSources { get; set; }
        public virtual ICollection<ACM_MeasuresToAssistFamily> ACM_MeasuresToAssistFamily { get; set; }
        public virtual ICollection<ACM_OtherPerson> ACM_OtherPersons { get; set; }
        public virtual ICollection<ACM_PermanencyPlan> ACM_PermanencyPlan { get; set; }
        public virtual ICollection<ACM_PrivateFamilyArrangements> ACM_PrivateFamilyArrangements { get; set; }
        public virtual ICollection<ACM_Recommendation> ACM_Recommendation { get; set; }
        public virtual ICollection<ACM_RecommendedAssistChild> ACM_RecommendedAssistChild { get; set; }
        public virtual ICollection<ACM_RecommendedAssistChildFamily> ACM_RecommendedAssistChildFamily { get; set; }
        public virtual ICollection<ACM_Siblings> ACM_Siblings { get; set; }
        public virtual ICollection<ACM_WrittenRequest> ACM_WrittenRequest { get; set; }
        public virtual ICollection<ACM_ChildrenConcerned> ACM_ChildrenConcerned { get; set; }
        public virtual ICollection<ACM_SpecialCurcumstances> ACM_SpecialCurcumstances { get; set; }
        public virtual ICollection<ACM_ViewsOfChildConcerned> ACM_ViewsOfChildConcerned { get; set; }
        public virtual ICollection<ACM_EvaluationRecommendationConclusion> ACM_EvaluationRecommendationConclusion { get; set; }
    }
}
