//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACM_DetailsOfChildParentsOrGuardian
    {
        public int DetailsOfChildParentsOrGuardian_Id { get; set; }
        public Nullable<int> Person_Id { get; set; }
        public string ApplicationForPassportOrConsentToRemoveChildReason { get; set; }
        public Nullable<System.DateTime> DateOfApplication { get; set; }
        public string WhereaboutsOfParentarentsOrguardianUnknownMotivation { get; set; }
        public string NameOfApplicant { get; set; }
        public Nullable<int> ConsentApplyPassportOrRemovalFromSA_Id { get; set; }
    
        public virtual ACM_ConsentApplyPassportOrRemovalFromSA ACM_ConsentApplyPassportOrRemovalFromSA { get; set; }
    }
}
