//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACM_ParticularsOfTheChildInAlternativeCare
    {
        public int ParticularsOfTheChildInAlternativeCare_Id { get; set; }
        public Nullable<int> PlacementType { get; set; }
        public string FileNumber { get; set; }
        public string CourtRefNumber { get; set; }
        public Nullable<int> Client_Id { get; set; }
        public Nullable<int> ConsentApplyPassportOrRemovalFromSA_Id { get; set; }
    
        public virtual ACM_ConsentApplyPassportOrRemovalFromSA ACM_ConsentApplyPassportOrRemovalFromSA { get; set; }
    }
}
