//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Action_Taken
    {
        public int Action_Taken_Id { get; set; }
        public int Incident_Id { get; set; }
        public int Office_Type_Id { get; set; }
        public Nullable<System.DateTime> Date_Action_Taken_Noted { get; set; }
        public string Action_Taken_Description { get; set; }
        public string Way_Forward_Description { get; set; }
    
        public virtual CPR_Incident CPR_Incident { get; set; }
        public virtual Office_Type Office_Type { get; set; }
    }
}
