//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public Address()
        {
            this.Schools = new HashSet<School>();
            this.Persons = new HashSet<Person>();
            this.apl_Employer = new HashSet<Employer>();
            this.CPR_Incidents = new HashSet<CPR_Incident>();
        }
    
        public int Address_Id { get; set; }
        public Nullable<int> Address_Type_Id { get; set; }
        public string Address_Line_1 { get; set; }
        public string Address_Line_2 { get; set; }
        public Nullable<int> Town_Id { get; set; }
        public string Postal_Code { get; set; }
    
        public virtual Address_Type Address_Type { get; set; }
        public virtual Town Town { get; set; }
        public virtual ICollection<School> Schools { get; set; }
        public virtual ICollection<Person> Persons { get; set; }
        public virtual ICollection<Employer> apl_Employer { get; set; }
        public virtual ICollection<CPR_Incident> CPR_Incidents { get; set; }
    }
}
