//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adopt_Adoption_Details
    {
        public int Adoption_Details_Id { get; set; }
        public Nullable<int> Court_Id { get; set; }
        public Nullable<System.DateTime> Finalised_Date { get; set; }
        public Nullable<int> Client_Id { get; set; }
        public Nullable<int> Client_Adoptive_Parent_Id { get; set; }
        public Nullable<int> Client_Reason_For_Adoption_Id { get; set; }
        public Nullable<int> Official_Responsible_Id { get; set; }
        public Nullable<int> Adoptive_Parent_Reason_For_Adoption_Id { get; set; }
        public Nullable<int> Adoption_Status_Id { get; set; }
        public Nullable<int> Form_Of_Notification_Id { get; set; }
        public string Organisation_Id { get; set; }
        public string Created_By { get; set; }
        public string Date_Created { get; set; }
        public string Modified_By { get; set; }
        public Nullable<int> Date_Modified { get; set; }
    
        public virtual Court apl_Court { get; set; }
        public virtual Employee apl_Employee { get; set; }
        public virtual Client_Adoptive_Parent int_Client_Adoptive_Parent { get; set; }
        public virtual apl_Adoption_Reason apl_Adoption_Reason { get; set; }
        public virtual apl_Adoption_Reason apl_Adoption_Reason1 { get; set; }
        public virtual apl_Adoption_Reason apl_Adoption_Reason2 { get; set; }
        public virtual apl_Form_Of_Notification apl_Form_Of_Notification { get; set; }
    }
}
