//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADOPT_Case_Details
    {
        public ADOPT_Case_Details()
        {
            this.ADOPT_OrgansationResponsible = new HashSet<ADOPT_OrgansationResponsible>();
        }
    
        public int Adopt_Case_Id { get; set; }
        public Nullable<int> Intake_Assessment_Id { get; set; }
        public Nullable<int> Client_Module_Id { get; set; }
        public Nullable<int> Organization_Id { get; set; }
        public Nullable<int> Court_Id { get; set; }
        public Nullable<System.DateTime> Date_Registered { get; set; }
        public string Court_Reffence { get; set; }
        public Nullable<System.DateTime> OdoptionOrder_Date { get; set; }
        public Nullable<int> Adoptions_Reason_Id { get; set; }
        public Nullable<int> Adopt_Type_Id { get; set; }
        public Nullable<int> Relationship_Type_Id { get; set; }
        public Nullable<int> NonRelation_Realtion_Id { get; set; }
        public Nullable<int> Adopting_Reason_Id { get; set; }
        public Nullable<int> Legitimacy_Id { get; set; }
        public string Adoption_Surname { get; set; }
        public Nullable<int> Cross_Cultural_Id { get; set; }
        public Nullable<int> Record_Status_Id { get; set; }
        public string Comments { get; set; }
        public Nullable<int> Created_By { get; set; }
        public Nullable<System.DateTime> Date_Created { get; set; }
        public Nullable<int> Modified_By { get; set; }
        public Nullable<System.DateTime> Date_Modified { get; set; }
        public Nullable<System.DateTime> Date_Finalised { get; set; }
        public Nullable<int> Adoption_Category_Id { get; set; }
    
        public virtual apl_Adopting_Reason apl_Adopting_Reason { get; set; }
        public virtual apl_Adoption_Reason apl_Adoption_Reason { get; set; }
        public virtual apl_Adoption_Relation_NonRelation apl_Adoption_Relation_NonRelation { get; set; }
        public virtual apl_Adoption_Type apl_Adoption_Type { get; set; }
        public virtual Court apl_Court { get; set; }
        public virtual Organization apl_Organization { get; set; }
        public virtual apl_Record_Status apl_Record_Status { get; set; }
        public virtual int_Client_Module_Registration int_Client_Module_Registration { get; set; }
        public virtual Intake_Assessment int_Intake_Assessment { get; set; }
        public virtual ICollection<ADOPT_OrgansationResponsible> ADOPT_OrgansationResponsible { get; set; }
    }
}
