//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADOPT_Letters
    {
        public int Adopt_Correspondence_Id { get; set; }
        public Nullable<int> Adopt_Case_Id { get; set; }
        public Nullable<int> Intake_Assessment_Id { get; set; }
        public Nullable<int> Correspondence_Type_Id { get; set; }
        public Nullable<System.DateTime> Adopt_Correspondence_Date_Created { get; set; }
        public Nullable<int> Adopt_Correspondence_Created_By { get; set; }
        public Nullable<System.DateTime> Adopt_Correspondence_Date_Modified { get; set; }
        public Nullable<int> Adopt_Correspondence_Modified_By { get; set; }
        public string Adopt_Correspondence_Comments { get; set; }
        public string Adopt_Correspondence_FileName { get; set; }
        public string Adopt_Correspondence_FilePath { get; set; }
    }
}
