//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alleged_Offender
    {
        public Alleged_Offender()
        {
            this.CPR_Section_153s = new HashSet<CPR_Section_153>();
            this.Convictions = new HashSet<CPR_Conviction>();
        }
    
        public int Alleged_Offender_Id { get; set; }
        public Nullable<int> Incident_Id { get; set; }
        public Nullable<int> Person_Id { get; set; }
        public bool Is_Known_Offender { get; set; }
        public Nullable<int> Child_Relationship_Type_Id { get; set; }
        public Nullable<int> Occupation_Id { get; set; }
        public string Passport { get; set; }
        public string Drivers_License { get; set; }
        public Nullable<int> Work_Address_Id { get; set; }
        public string Whereabouts { get; set; }
    
        public virtual CPR_Incident CPR_Incident { get; set; }
        public virtual Person Person { get; set; }
        public virtual Relationship_Type Relationship_Type { get; set; }
        public virtual ICollection<CPR_Section_153> CPR_Section_153s { get; set; }
        public virtual ICollection<CPR_Conviction> Convictions { get; set; }
    }
}
