//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class apl_AuditTrial
    {
        public int apl_AuditTrial_Id { get; set; }
        public string taskperformed { get; set; }
        public Nullable<System.DateTime> datecaptured { get; set; }
        public string module { get; set; }
        public string username { get; set; }
        public string serviceoffice { get; set; }
        public string organisation { get; set; }
    }
}
