//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class apl_Place_Of_Detention
    {
        public int Place_Of_Detention_Id { get; set; }
        public string Description { get; set; }
        public Nullable<int> District_Id { get; set; }
    }
}
