//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class apl_PCM_Charges
    {
        public int Charge_Id { get; set; }
        public string Charge_Description { get; set; }
        public string Charge_Code { get; set; }
        public string Offense_Code { get; set; }
    }
}
