//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class apl_Record_Status
    {
        public apl_Record_Status()
        {
            this.ACM_CaseWorkList = new HashSet<ACM_CaseWorkList>();
            this.ADOPT_Case_Details = new HashSet<ADOPT_Case_Details>();
        }
    
        public int Record_Status_Id { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<ACM_CaseWorkList> ACM_CaseWorkList { get; set; }
        public virtual ICollection<ADOPT_Case_Details> ADOPT_Case_Details { get; set; }
    }
}
