//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class apl_Form_Of_Notification
    {
        public apl_Form_Of_Notification()
        {
            this.Adopt_Adoption_Details = new HashSet<Adopt_Adoption_Details>();
        }
    
        public int Form_Of_Notification_Id { get; set; }
        public string Description { get; set; }
        public string Source { get; set; }
        public string Definition { get; set; }
    
        public virtual ICollection<Adopt_Adoption_Details> Adopt_Adoption_Details { get; set; }
    }
}
