//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class apl_Cyca_Facility_Programs
    {
        public int Program_Id { get; set; }
        public string Program_Name { get; set; }
        public string Program_Description { get; set; }
        public string Program_Capacity { get; set; }
        public string Program_Duration { get; set; }
        public Nullable<System.DateTime> Program_StartDate { get; set; }
        public Nullable<System.DateTime> Program_EndDate { get; set; }
        public Nullable<int> Section_Id { get; set; }
        public Nullable<int> Staff_Id { get; set; }
        public Nullable<int> Venue_Id { get; set; }
        public string Sponoser_Details { get; set; }
        public Nullable<int> Facility_Id { get; set; }
    }
}
