//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class apl_Adoption_Reason
    {
        public apl_Adoption_Reason()
        {
            this.Adopt_Adoption_Details = new HashSet<Adopt_Adoption_Details>();
            this.Adopt_Adoption_Details1 = new HashSet<Adopt_Adoption_Details>();
            this.Adopt_Adoption_Details2 = new HashSet<Adopt_Adoption_Details>();
            this.ADOPT_Case_Details = new HashSet<ADOPT_Case_Details>();
        }
    
        public int Adoptions_Reason_Id { get; set; }
        public string Description { get; set; }
        public string Defination { get; set; }
        public string Source { get; set; }
    
        public virtual ICollection<Adopt_Adoption_Details> Adopt_Adoption_Details { get; set; }
        public virtual ICollection<Adopt_Adoption_Details> Adopt_Adoption_Details1 { get; set; }
        public virtual ICollection<Adopt_Adoption_Details> Adopt_Adoption_Details2 { get; set; }
        public virtual ICollection<ADOPT_Case_Details> ADOPT_Case_Details { get; set; }
    }
}
