//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class apl_Cyca_Facility
    {
        public int Facility_Id { get; set; }
        public string FacilityName { get; set; }
        public string OfficialCapacity { get; set; }
        public string FacilityAddress { get; set; }
        public string FacilityFaxNo { get; set; }
        public string FacilityEmailAddress { get; set; }
        public string FacilityTelNo { get; set; }
        public string FacilityAccro { get; set; }
        public Nullable<int> Province_Id { get; set; }
        public Nullable<int> Admission_Type_Id { get; set; }
    }
}
