//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class apl_Programmes
    {
        public int Programme_Id { get; set; }
        public string Programme_Name { get; set; }
        public string Programme_Description { get; set; }
        public Nullable<System.DateTime> Programme_StartDate { get; set; }
        public Nullable<System.DateTime> Programme_EndDate { get; set; }
        public Nullable<int> Programme_Type_Id { get; set; }
        public Nullable<int> Organization_Id { get; set; }
        public Nullable<int> Programme_Category_Id { get; set; }
    }
}
