//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class apl_DisabilityType
    {
        public int DisabilityType_Id { get; set; }
        public Nullable<int> DisabilityId { get; set; }
        public string TypeName { get; set; }
    
        public virtual Disability apl_Disability { get; set; }
    }
}
