//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public Client()
        {
            this.Client_Adoptive_Parents = new HashSet<Client_Adoptive_Parent>();
            this.Client_Biological_Parents = new HashSet<Client_Biological_Parent>();
            this.Client_Foster_Parents = new HashSet<Client_Foster_Parent>();
            this.Client_Family_Members = new HashSet<Client_Family_Member>();
            this.Client_CareGivers = new HashSet<Client_CareGiver>();
            this.Intake_Assessments = new HashSet<Intake_Assessment>();
            this.int_Client_Module_Registration = new HashSet<int_Client_Module_Registration>();
            this.int_Client_Prospective_Adoptive_Parent = new HashSet<int_Client_Prospective_Adoptive_Parent>();
            this.int_Client_ProspectiveAdoptiveParents = new HashSet<int_Client_ProspectiveAdoptiveParents>();
        }
    
        public int Client_Id { get; set; }
        public Nullable<int> Person_Id { get; set; }
        public string Reference_Number { get; set; }
        public System.DateTime Date_Created { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Date_Last_Modified { get; set; }
        public string Modified_By { get; set; }
        public bool Is_Active { get; set; }
        public bool Is_Deleted { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual ICollection<Client_Adoptive_Parent> Client_Adoptive_Parents { get; set; }
        public virtual ICollection<Client_Biological_Parent> Client_Biological_Parents { get; set; }
        public virtual ICollection<Client_Foster_Parent> Client_Foster_Parents { get; set; }
        public virtual ICollection<Client_Family_Member> Client_Family_Members { get; set; }
        public virtual ICollection<Client_CareGiver> Client_CareGivers { get; set; }
        public virtual ICollection<Intake_Assessment> Intake_Assessments { get; set; }
        public virtual ICollection<int_Client_Module_Registration> int_Client_Module_Registration { get; set; }
        public virtual ICollection<int_Client_Prospective_Adoptive_Parent> int_Client_Prospective_Adoptive_Parent { get; set; }
        public virtual ICollection<int_Client_ProspectiveAdoptiveParents> int_Client_ProspectiveAdoptiveParents { get; set; }
    }
}
