//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Correspondence_Type
    {
        public Correspondence_Type()
        {
            this.CPR_Incident_Correspondence_Items = new HashSet<Incident_Correspondence>();
        }
    
        public int Correspondence_Type_Id { get; set; }
        public string Description { get; set; }
        public string Source { get; set; }
        public string Definition { get; set; }
        public string Correspondence_Content { get; set; }
    
        public virtual ICollection<Incident_Correspondence> CPR_Incident_Correspondence_Items { get; set; }
    }
}
