//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Court_Outcome_Item
    {
        public Court_Outcome_Item()
        {
            this.CPR_Childrens_Court_Detail = new HashSet<CPR_Childrens_Court_Detail>();
            this.Child_Court_Outcome_Items = new HashSet<Court_Outcome_Item>();
        }
    
        public int Court_Outcome_Id { get; set; }
        public string Item_Number { get; set; }
        public string Description { get; set; }
        public string Source { get; set; }
        public string Definition { get; set; }
        public Nullable<int> Parent_Id { get; set; }
        public bool Is_Heading { get; set; }
    
        public virtual ICollection<CPR_Childrens_Court_Detail> CPR_Childrens_Court_Detail { get; set; }
        public virtual ICollection<Court_Outcome_Item> Child_Court_Outcome_Items { get; set; }
        public virtual Court_Outcome_Item Parent_Court_Outcome_Item { get; set; }
    }
}
