//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Court
    {
        public Court()
        {
            this.CPR_Convictions = new HashSet<CPR_Conviction>();
            this.CPR_Unsuitability_Conviction = new HashSet<CPR_Unsuitability_Conviction>();
            this.CPR_Childrens_Court_Detail_Items = new HashSet<CPR_Childrens_Court_Detail>();
            this.Adopt_Adoption_Details = new HashSet<Adopt_Adoption_Details>();
            this.ADOPT_Case_Details = new HashSet<ADOPT_Case_Details>();
            this.PCM_Case_Details = new HashSet<PCM_Case_Details>();
        }
    
        public int Court_Id { get; set; }
        public Nullable<int> District_Id { get; set; }
        public string Description { get; set; }
    
        public virtual District District { get; set; }
        public virtual ICollection<CPR_Conviction> CPR_Convictions { get; set; }
        public virtual ICollection<CPR_Unsuitability_Conviction> CPR_Unsuitability_Conviction { get; set; }
        public virtual ICollection<CPR_Childrens_Court_Detail> CPR_Childrens_Court_Detail_Items { get; set; }
        public virtual ICollection<Adopt_Adoption_Details> Adopt_Adoption_Details { get; set; }
        public virtual ICollection<ADOPT_Case_Details> ADOPT_Case_Details { get; set; }
        public virtual ICollection<PCM_Case_Details> PCM_Case_Details { get; set; }
    }
}
