//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPR_OnlineNotifications_Incedent
    {
        public int Incedent_Id { get; set; }
        public Nullable<System.DateTime> DateOfIncedent { get; set; }
        public Nullable<int> AbuseType_Id { get; set; }
        public Nullable<int> ImediateDanger { get; set; }
        public Nullable<int> RiskToChild_Id { get; set; }
        public string Reason { get; set; }
        public string Location { get; set; }
    }
}
