//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPR_EnquiriesEmployerDetails
    {
        public int Employer_Id { get; set; }
        public Nullable<int> Enquiry_Id { get; set; }
        public string BusinessName { get; set; }
        public string TradingAs { get; set; }
        public string TheManager { get; set; }
        public Nullable<int> Title_Id { get; set; }
        public string ContactFirstName { get; set; }
        public string ContactSurname { get; set; }
        public string ContactTelephoneNumber { get; set; }
        public string ContactMobileNumber { get; set; }
        public string PhysicalAddress1 { get; set; }
        public string PhysicalAddress2 { get; set; }
        public string PhysicalPostalCode { get; set; }
        public string PostalAddress1 { get; set; }
        public string PostalAddress2 { get; set; }
        public string PostalCode { get; set; }
        public Nullable<int> MagisterialDistrict_Id { get; set; }
        public Nullable<int> CityTown_Id { get; set; }
        public Nullable<int> Province_Id { get; set; }
        public string CurrentPosition { get; set; }
        public string PositionAppliedFor { get; set; }
    
        public virtual CPR_EnquiriesByEmployer CPR_EnquiriesByEmployer { get; set; }
    }
}
