//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPR_EnquiriesByIndividual
    {
        public int Enquiry_Id { get; set; }
        public bool IdentityDocument { get; set; }
        public bool Passport { get; set; }
        public bool BirthCertificate { get; set; }
        public System.DateTime DateOfEnquiry { get; set; }
        public string WhoEnquired { get; set; }
        public Nullable<int> PersonDetails_Id { get; set; }
        public Nullable<int> LoggedInUserId { get; set; }
        public string ReferenceNumber { get; set; }
    }
}
