//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPR_APPEALS
    {
        public int Appeal_Id { get; set; }
        public int Person_Id { get; set; }
        public Nullable<int> Conviction_Id { get; set; }
        public Nullable<System.DateTime> DateNoticeRecieved { get; set; }
        public string ReasonForDispute { get; set; }
        public Nullable<System.DateTime> LetterOfNoticeSubmitted { get; set; }
        public Nullable<System.DateTime> DateAppealLogged { get; set; }
        public string CourtOrderAvailable { get; set; }
        public Nullable<System.DateTime> DateOfCourtOrder { get; set; }
        public Nullable<int> AppealResult_Id { get; set; }
        public string Whereabouts { get; set; }
        public Nullable<bool> IsRemoved { get; set; }
        public Nullable<int> Gender_Id { get; set; }
        public Nullable<int> Relationship_Type_Id { get; set; }
        public Nullable<int> Province_Id { get; set; }
        public Nullable<int> Magisterial_Id { get; set; }
        public Nullable<int> CityTown_Id { get; set; }
    }
}
