//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPR_Title
    {
        public CPR_Title()
        {
            this.CPR_EquiriesPersonDetails = new HashSet<CPR_EquiriesPersonDetails>();
        }
    
        public int Title_Id { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<CPR_EquiriesPersonDetails> CPR_EquiriesPersonDetails { get; set; }
    }
}
