//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPR_Unsuitability_Findings
    {
        public int Findings_Id { get; set; }
        public int Findings_Type_Id { get; set; }
        public int Unsuitability_Id { get; set; }
        public bool IsGuilty { get; set; }
        public bool RequestAppeal { get; set; }
        public string Reason { get; set; }
        public System.DateTime DateOfFinding { get; set; }
    
        public virtual CPR_Finding_Type CPR_Finding_Type { get; set; }
        public virtual CPR_Unsuitability CPR_Unsuitability { get; set; }
    }
}
