//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPR_OnlineNotification__ChildDetails
    {
        public int ChildDetails_Id { get; set; }
        public string Fullnames { get; set; }
        public string Surname { get; set; }
        public string KnownAs { get; set; }
        public string IDNumber { get; set; }
        public string Age { get; set; }
        public Nullable<int> Gender_Id { get; set; }
        public string LastKnowAddress { get; set; }
        public Nullable<int> Province_Id { get; set; }
        public Nullable<int> Magistrates_Id { get; set; }
        public Nullable<int> City_Id { get; set; }
        public Nullable<int> Incedent_Id { get; set; }
        public Nullable<int> AllegedOffender_Id { get; set; }
        public Nullable<int> FirstReporter_Id { get; set; }
        public Nullable<int> Reporter_Id { get; set; }
        public Nullable<int> MandatoryReporter_Id { get; set; }
        public string ReferenceNumber { get; set; }
    }
}
