//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPR_OnlineNotification_FirstReporter
    {
        public int FirstReporter_Id { get; set; }
        public bool ReportedByAnother { get; set; }
        public string Fullnames { get; set; }
        public string Surname { get; set; }
        public string TelephoneNumber { get; set; }
        public string CelphoneNumber { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<int> Relation_Id { get; set; }
    }
}
