//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPR_Unsuitability_Conviction
    {
        public int Conviction_Id { get; set; }
        public int Unsuitability_Id { get; set; }
        public string J14_Reference_Number { get; set; }
        public string SAPS_Case_Number { get; set; }
        public Nullable<int> Court_Id { get; set; }
        public string Conviction { get; set; }
        public Nullable<System.DateTime> DateOfConviction { get; set; }
        public string Sentence { get; set; }
        public string BriefAccount { get; set; }
        public string CourtReferenceNumber { get; set; }
        public string PlaceOfOffence { get; set; }
        public string NatureOfCharge { get; set; }
        public string SummaryOfCourtFinding { get; set; }
        public string CourtType { get; set; }
        public string CourtAddress { get; set; }
    
        public virtual Court apl_Court { get; set; }
        public virtual CPR_Unsuitability CPR_Unsuitability { get; set; }
    }
}
