//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPR_EquiriesPersonDetails
    {
        public int PersonDetails_Id { get; set; }
        public Nullable<int> Enquiry_Id { get; set; }
        public string Surname { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string NickName { get; set; }
        public string IdNumber { get; set; }
        public string MobileNumber { get; set; }
        public string TelephoneNumber { get; set; }
        public Nullable<int> Province_Id { get; set; }
        public Nullable<int> MagiserialDistrinct_Id { get; set; }
        public Nullable<int> CityTown_Id { get; set; }
        public string PhysicalAddress1 { get; set; }
        public string PhysicalAddress2 { get; set; }
        public string PhysicalPostalCode { get; set; }
        public string PostalAddress1 { get; set; }
        public string PostalAddress2 { get; set; }
        public string PostalCode { get; set; }
        public string CurrentPosition { get; set; }
        public string PositionAppliedFor { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<int> Title_Id { get; set; }
    
        public virtual CPR_Title CPR_Title { get; set; }
    }
}
