//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPR_Unsuitability_Ruiling
    {
        public int Ruiling_Id { get; set; }
        public int RuilingType_Id { get; set; }
        public Nullable<int> Unsuitability_Id { get; set; }
        public string Reason { get; set; }
        public bool RequestAppeal { get; set; }
        public Nullable<System.DateTime> DateOfRuiling { get; set; }
    
        public virtual CPR_Ruiling_Type CPR_Ruiling_Type { get; set; }
        public virtual CPR_Unsuitability CPR_Unsuitability { get; set; }
    }
}
