//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPR_Unsuitability
    {
        public CPR_Unsuitability()
        {
            this.CPR_Unsuitability_Conviction = new HashSet<CPR_Unsuitability_Conviction>();
            this.CPR_Unsuitability_Findings = new HashSet<CPR_Unsuitability_Findings>();
            this.CPR_Unsuitability_Forum = new HashSet<CPR_Unsuitability_Forum>();
            this.CPR_Unsuitability_Incedent = new HashSet<CPR_Unsuitability_Incedent>();
            this.CPR_Unsuitability_Ruiling = new HashSet<CPR_Unsuitability_Ruiling>();
        }
    
        public int Unsuitablity_Id { get; set; }
        public int Person_Id { get; set; }
        public string CPRB_ReferenceNumber { get; set; }
        public bool FingerPrints { get; set; }
        public bool Photo { get; set; }
        public bool CourtOrder { get; set; }
        public bool CourtFindings { get; set; }
        public bool KnownOffender { get; set; }
        public bool InternationalNotification { get; set; }
        public int RelationshipType_Id { get; set; }
        public string DriversLicenseNumber { get; set; }
        public string PrisonerIdentityNumber { get; set; }
        public int RegistrationType { get; set; }
        public Nullable<System.DateTime> DateRegistered { get; set; }
        public Nullable<System.DateTime> NotificationDate { get; set; }
        public int Employer_Id { get; set; }
        public int Tiitle_Id { get; set; }
        public Nullable<int> Findings_Id { get; set; }
        public Nullable<int> Child_Id { get; set; }
        public Nullable<int> Conviction_Id { get; set; }
        public Nullable<int> CareGiver_Id { get; set; }
        public Nullable<int> Incident_Id { get; set; }
        public Nullable<int> Forum_Id { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool MinutesOfForum { get; set; }
        public Nullable<int> CityTown_Id { get; set; }
        public Nullable<int> MagisterialDistrict_Id { get; set; }
        public Nullable<int> Province_Id { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<bool> IsRemoved { get; set; }
        public Nullable<System.DateTime> RemovalDate { get; set; }
        public string PostalCode { get; set; }
        public string WhereAbouts { get; set; }
        public string WorkAddAddLine1 { get; set; }
        public string WorkAddAddLine2 { get; set; }
        public string WorkAddPosCode { get; set; }
        public Nullable<int> Occupation_Id { get; set; }
    
        public virtual District apl_District { get; set; }
        public virtual Town apl_Town { get; set; }
        public virtual ICollection<CPR_Unsuitability_Conviction> CPR_Unsuitability_Conviction { get; set; }
        public virtual ICollection<CPR_Unsuitability_Findings> CPR_Unsuitability_Findings { get; set; }
        public virtual ICollection<CPR_Unsuitability_Forum> CPR_Unsuitability_Forum { get; set; }
        public virtual ICollection<CPR_Unsuitability_Incedent> CPR_Unsuitability_Incedent { get; set; }
        public virtual Person int_Person { get; set; }
        public virtual ICollection<CPR_Unsuitability_Ruiling> CPR_Unsuitability_Ruiling { get; set; }
    }
}
