//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPR_Section_153
    {
        public CPR_Section_153()
        {
            this.Section_153_Items = new HashSet<Section_153_Item>();
        }
    
        public int Section_153_Id { get; set; }
        public int Alleged_Offender_Id { get; set; }
        public bool Is_Notice_Granted { get; set; }
        public Nullable<System.DateTime> Date_Notice_Granted { get; set; }
        public bool Is_Notice_Issued { get; set; }
        public Nullable<System.DateTime> Date_Notice_Issued { get; set; }
    
        public virtual Alleged_Offender CPR_Alleged_Offender { get; set; }
        public virtual ICollection<Section_153_Item> Section_153_Items { get; set; }
    }
}
