//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPR_EnquiriesByEmployer
    {
        public CPR_EnquiriesByEmployer()
        {
            this.CPR_EnquiriesEmployerDetails = new HashSet<CPR_EnquiriesEmployerDetails>();
        }
    
        public int Enquiry_Id { get; set; }
        public bool IdDocument { get; set; }
        public bool Passport { get; set; }
        public bool BusinessLetterHead { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public string PositionHeld { get; set; }
        public System.DateTime DateOfEnquiry { get; set; }
        public Nullable<int> LoggedInUserId { get; set; }
        public string ReferenceNumber { get; set; }
    
        public virtual ICollection<CPR_EnquiriesEmployerDetails> CPR_EnquiriesEmployerDetails { get; set; }
    }
}
