//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPR_Finding_Type
    {
        public CPR_Finding_Type()
        {
            this.CPR_Unsuitability_Findings = new HashSet<CPR_Unsuitability_Findings>();
        }
    
        public int FindingType_Id { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<CPR_Unsuitability_Findings> CPR_Unsuitability_Findings { get; set; }
    }
}
