//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPR_Conviction
    {
        public int CPR_Conviction_Id { get; set; }
        public int Alleged_Offender_Id { get; set; }
        public string J14_Reference_Number { get; set; }
        public string SAPS_Case_Number { get; set; }
        public Nullable<int> Court_Id { get; set; }
        public string Conviction { get; set; }
        public string Nature_Of_Charge { get; set; }
        public string Sentence { get; set; }
        public Nullable<System.DateTime> Date_Sentenced { get; set; }
        public string Account_Of_Charge_And_Conviction { get; set; }
    
        public virtual Alleged_Offender CPR_Alleged_Offender { get; set; }
        public virtual Court Court { get; set; }
    }
}
