//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPR_Correspondence_Letter
    {
        public CPR_Correspondence_Letter()
        {
            this.CPR_Correspondence = new HashSet<CPR_Correspondence>();
        }
    
        public int CPR_Correspondence_Letter_Id { get; set; }
        public string Description { get; set; }
        public string Letter_Content { get; set; }
        public string Source { get; set; }
        public string Definition { get; set; }
    
        public virtual ICollection<CPR_Correspondence> CPR_Correspondence { get; set; }
    }
}
