//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPR_OnlineNotification_AlledgedOffender
    {
        public int AllegedOffender_Id { get; set; }
        public bool HaveInformation { get; set; }
        public string FullName { get; set; }
        public string Surname { get; set; }
        public string KnownAs { get; set; }
        public string IdNumber { get; set; }
        public Nullable<int> Gender_Id { get; set; }
        public string LastKnownAddress { get; set; }
        public Nullable<int> Province_Id { get; set; }
        public Nullable<int> MagistrateDistrict_Id { get; set; }
        public Nullable<int> City_Id { get; set; }
        public string Whereabout { get; set; }
        public Nullable<int> Relation_Id { get; set; }
    }
}
