//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPR_OnlineNotification_MandatoryReporter
    {
        public int Reporter_Id { get; set; }
        public Nullable<int> Obliged_Id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string EmailAddress { get; set; }
        public string TelephoneNumber { get; set; }
        public string Cellphone { get; set; }
        public Nullable<int> Province_Id { get; set; }
        public Nullable<int> Magisterial_Id { get; set; }
        public Nullable<int> City_Id { get; set; }
        public string NameOfOrg { get; set; }
    }
}
