//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPR_SAPS_Reported_Police_Station_History
    {
        public int Reported_Police_Station_History_Item_Id { get; set; }
        public int SAPS_Detail_Id { get; set; }
        public System.DateTime Item_Date { get; set; }
        public int Reported_Police_Station_Id { get; set; }
    
        public virtual SAPS_Station apl_SAPS_Station { get; set; }
        public virtual CPR_SAPS_Detail CPR_SAPS_Detail { get; set; }
    }
}
