//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPR_Unsuitability_Incedent
    {
        public int Incedent_Id { get; set; }
        public int Unsuitability_Id { get; set; }
        public int Abuse_Type_Id { get; set; }
        public string PreviousHistory { get; set; }
        public Nullable<System.DateTime> DateOfOffence { get; set; }
        public string SpecifyTypeOfAbuse { get; set; }
        public Nullable<int> Selected_Abuse_Indicator_Id { get; set; }
    
        public virtual Abuse_Type apl_Abuse_Type { get; set; }
        public virtual CPR_Unsuitability CPR_Unsuitability { get; set; }
    }
}
