//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPR_Ruiling_Type
    {
        public CPR_Ruiling_Type()
        {
            this.CPR_Unsuitability_Ruiling = new HashSet<CPR_Unsuitability_Ruiling>();
        }
    
        public int RuilingType_Id { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<CPR_Unsuitability_Ruiling> CPR_Unsuitability_Ruiling { get; set; }
    }
}
