//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPR_SAPS_Investigating_Officer_History
    {
        public int Investigating_Officer_History_Item_Id { get; set; }
        public int SAPS_Detail_Id { get; set; }
        public System.DateTime Item_Date { get; set; }
        public int Investigating_Officer_Id { get; set; }
    
        public virtual SAPS_Official apl_SAPS_Official { get; set; }
        public virtual CPR_SAPS_Detail CPR_SAPS_Detail { get; set; }
    }
}
