//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPR_SAPS_Detail
    {
        public CPR_SAPS_Detail()
        {
            this.CPR_SAPS_Investigating_Officer_History = new HashSet<CPR_SAPS_Investigating_Officer_History>();
            this.CPR_SAPS_Reported_Police_Station_History = new HashSet<CPR_SAPS_Reported_Police_Station_History>();
        }
    
        public int SAPS_Detail_Id { get; set; }
        public int Incident_Id { get; set; }
        public bool Is_Reported_To_SAPS { get; set; }
        public Nullable<System.DateTime> Date_Case_Reported { get; set; }
        public string Case_Number { get; set; }
        public bool Is_Police_Intervention { get; set; }
        public Nullable<int> Reported_Police_Station_Id { get; set; }
        public Nullable<int> Investigating_Officer_Id { get; set; }
        public string Comments { get; set; }
    
        public virtual CPR_Incident CPR_Incident { get; set; }
        public virtual SAPS_Official SAPS_Official { get; set; }
        public virtual SAPS_Station SAPS_Station { get; set; }
        public virtual ICollection<CPR_SAPS_Investigating_Officer_History> CPR_SAPS_Investigating_Officer_History { get; set; }
        public virtual ICollection<CPR_SAPS_Reported_Police_Station_History> CPR_SAPS_Reported_Police_Station_History { get; set; }
    }
}
