//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class District
    {
        public District()
        {
            this.Paypoints = new HashSet<Paypoint>();
            this.Courts = new HashSet<Court>();
            this.CPR_Incidents = new HashSet<CPR_Incident>();
            this.CPR_Unsuitability = new HashSet<CPR_Unsuitability>();
            this.LocalMunicipalities = new HashSet<Local_Municipality>();
        }
    
        public int District_Id { get; set; }
        public int Province_Id { get; set; }
        public string Description { get; set; }
    
        public virtual Province Province { get; set; }
        public virtual ICollection<Paypoint> Paypoints { get; set; }
        public virtual ICollection<Court> Courts { get; set; }
        public virtual ICollection<CPR_Incident> CPR_Incidents { get; set; }
        public virtual ICollection<CPR_Unsuitability> CPR_Unsuitability { get; set; }
        public virtual ICollection<Local_Municipality> LocalMunicipalities { get; set; }
    }
}
