//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.Subordinate_Employees = new HashSet<Employee>();
            this.Supervised_Employees = new HashSet<Employee>();
            this.Adopt_Adoption_Details = new HashSet<Adopt_Adoption_Details>();
            this.EmployeeServices = new HashSet<EmployeeService>();
            this.EmployeeRoles = new HashSet<EmployeeRole>();
        }
    
        public int Employee_Id { get; set; }
        public int User_Id { get; set; }
        public string Persal_Number { get; set; }
        public Nullable<int> Head_Of_Department_Id { get; set; }
        public Nullable<int> Supervisor_Id { get; set; }
        public string Phone_Number { get; set; }
        public string Mobile_Phone_Number { get; set; }
        public Nullable<int> Gender_Id { get; set; }
        public Nullable<int> Race_Id { get; set; }
        public string ID_Number { get; set; }
        public Nullable<int> Job_Position_Id { get; set; }
        public Nullable<int> Paypoint_Id { get; set; }
        public int Service_Office_Id { get; set; }
        public Nullable<int> Salary_Level_Id { get; set; }
        public bool Is_Shift_Worker { get; set; }
        public bool Is_Casual_Worker { get; set; }
        public System.DateTime Date_Created { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Date_Last_Modified { get; set; }
        public string Modified_By { get; set; }
        public bool Is_Active { get; set; }
        public bool Is_Deleted { get; set; }
        public bool Is_SocialWorker { get; set; }
        public Nullable<int> Organization_Id { get; set; }
    
        public virtual User User { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual Job_Position Job_Position { get; set; }
        public virtual Paypoint Paypoint { get; set; }
        public virtual Race Race { get; set; }
        public virtual Salary_Level Salary_Level { get; set; }
        public virtual ICollection<Employee> Subordinate_Employees { get; set; }
        public virtual Employee Head_of_Department { get; set; }
        public virtual ICollection<Employee> Supervised_Employees { get; set; }
        public virtual Employee Supervisor { get; set; }
        public virtual ICollection<Adopt_Adoption_Details> Adopt_Adoption_Details { get; set; }
        public virtual Service_Office apl_Service_Office { get; set; }
        public virtual ICollection<EmployeeService> EmployeeServices { get; set; }
        public virtual ICollection<EmployeeRole> EmployeeRoles { get; set; }
    }
}
