//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Incident_Abuse_Type
    {
        public int Incident_Abuse_Type_Id { get; set; }
        public int Incident_Id { get; set; }
        public int Abuse_Type_Id { get; set; }
        public bool Is_Primary_Abuse_Type { get; set; }
    
        public virtual Abuse_Type Abuse_Type { get; set; }
        public virtual CPR_Incident CPR_Incident { get; set; }
    }
}
