//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Incident_Monitoring_ChildrensCourt_Extension
    {
        public int Monitoring_Extension_Id { get; set; }
        public int Incident_Monitoring_Id { get; set; }
        public System.DateTime Extension_Date { get; set; }
    
        public virtual Incident_Monitoring_Item CPR_Incident_Monitoring_Item { get; set; }
    }
}
