//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Incident_Correspondence
    {
        public int Incident_Correspondence_Id { get; set; }
        public int Incident_Id { get; set; }
        public int Correspondence_Type_Id { get; set; }
        public System.DateTime Date_Correspondence_Sent { get; set; }
    
        public virtual Correspondence_Type Correspondence_Type { get; set; }
        public virtual CPR_Incident CPR_Incident { get; set; }
    }
}
