//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Informant_Capacity_Type
    {
        public Informant_Capacity_Type()
        {
            this.CPR_Informant = new HashSet<CPR_Informant>();
        }
    
        public int Informant_Capacity_Type_Id { get; set; }
        public string Description { get; set; }
        public string Source { get; set; }
        public string Definition { get; set; }
    
        public virtual ICollection<CPR_Informant> CPR_Informant { get; set; }
    }
}
