//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class int_Client_Module_Registration
    {
        public int_Client_Module_Registration()
        {
            this.Adopt_Case_Initiation = new HashSet<Adopt_Case_Initiation>();
            this.ADOPT_Case_Details = new HashSet<ADOPT_Case_Details>();
            this.PCM_Case_Details = new HashSet<PCM_Case_Details>();
        }
    
        public int Client_Module_Id { get; set; }
        public int Module_Id { get; set; }
        public int Client_Id { get; set; }
        public string Client_Module_Ref_No { get; set; }
    
        public virtual ICollection<Adopt_Case_Initiation> Adopt_Case_Initiation { get; set; }
        public virtual Module apl_Module { get; set; }
        public virtual Client int_Client { get; set; }
        public virtual ICollection<ADOPT_Case_Details> ADOPT_Case_Details { get; set; }
        public virtual ICollection<PCM_Case_Details> PCM_Case_Details { get; set; }
    }
}
