//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class int_Reporting_Person
    {
        public int Reporting_Person_Id { get; set; }
        public int Person_Id { get; set; }
        public bool Is_Anonymous { get; set; }
        public Nullable<int> Relationship_Type_Id { get; set; }
    }
}
