//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Intake_Assessment
    {
        public Intake_Assessment()
        {
            this.Referral_Focus_Areas = new HashSet<Referral_Focus_Area>();
            this.CPR_Incident = new HashSet<CPR_Incident>();
            this.ACM_CaseWorkList = new HashSet<ACM_CaseWorkList>();
            this.Adopt_Case_Initiation = new HashSet<Adopt_Case_Initiation>();
            this.RACAP_Adoptive_Child = new HashSet<RACAP_Adoptive_Child>();
            this.RACAP_Case_WorkList = new HashSet<RACAP_Case_WorkList>();
            this.RACAP_Prospective_Parent = new HashSet<RACAP_Prospective_Parent>();
            this.ADOPT_Case_WorkList = new HashSet<ADOPT_Case_WorkList>();
            this.ADOPT_Case_Details = new HashSet<ADOPT_Case_Details>();
            this.RACAP_OrgansationResponsible = new HashSet<RACAP_OrgansationResponsible>();
            this.RACAP_Case_Details = new HashSet<RACAP_Case_Details>();
            this.PCM_Case_Details = new HashSet<PCM_Case_Details>();
            this.PCM_Previous_Involvement_Details = new HashSet<PCM_Previous_Involvement_Details>();
            this.PCM_Recommendation = new HashSet<PCM_Recommendation>();
            this.PCM_Victim_Details = new HashSet<PCM_Victim_Details>();
            this.PCM_Victim_Organisation_Details = new HashSet<PCM_Victim_Organisation_Details>();
            this.PCM_WorkList = new HashSet<PCM_WorkList>();
        }
    
        public int Intake_Assessment_Id { get; set; }
        public int Client_Id { get; set; }
        public System.DateTime Assessment_Date { get; set; }
        public Nullable<int> Assessed_By_Id { get; set; }
        public Nullable<int> Case_Manager_Supervisor_Id { get; set; }
        public Nullable<int> Case_Manager_Id { get; set; }
        public string Preliminary_Assessment { get; set; }
        public string Presenting_Problem { get; set; }
        public Nullable<int> Problem_Sub_Category_Id { get; set; }
        public bool Is_Closed { get; set; }
        public Nullable<System.DateTime> ClosedDate { get; set; }
        public Nullable<System.DateTime> Treatment_Date { get; set; }
        public Nullable<int> Intervention_Id { get; set; }
        public bool Is_Referred_For_Assessment { get; set; }
        public bool Is_Referred_To_Other_Service_Provider { get; set; }
        public string Case_Background { get; set; }
        public string Supervisor_Comments { get; set; }
        public string Social_Worker_Comments { get; set; }
        public Nullable<int> Referred_From_Organization_Id { get; set; }
        public Nullable<int> Referred_To_Organization_Id { get; set; }
        public System.DateTime Date_Created { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Date_Last_Modified { get; set; }
        public string Modified_By { get; set; }
        public bool Is_Active { get; set; }
        public bool Is_Deleted { get; set; }
        public bool Is_Priority_Intervention { get; set; }
        public string Case_Allocation_Comments { get; set; }
        public Nullable<System.DateTime> Date_Allocated { get; set; }
        public Nullable<System.DateTime> Date_Due { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Problem_Sub_Category Problem_Sub_Category { get; set; }
        public virtual ICollection<Referral_Focus_Area> Referral_Focus_Areas { get; set; }
        public virtual Organization Referred_From_Organization { get; set; }
        public virtual Organization Referred_To_Organization { get; set; }
        public virtual User Case_Manager_Supervisor { get; set; }
        public virtual User Case_Manager { get; set; }
        public virtual User Assessor { get; set; }
        public virtual ICollection<CPR_Incident> CPR_Incident { get; set; }
        public virtual ICollection<ACM_CaseWorkList> ACM_CaseWorkList { get; set; }
        public virtual ICollection<Adopt_Case_Initiation> Adopt_Case_Initiation { get; set; }
        public virtual ICollection<RACAP_Adoptive_Child> RACAP_Adoptive_Child { get; set; }
        public virtual ICollection<RACAP_Case_WorkList> RACAP_Case_WorkList { get; set; }
        public virtual ICollection<RACAP_Prospective_Parent> RACAP_Prospective_Parent { get; set; }
        public virtual ICollection<ADOPT_Case_WorkList> ADOPT_Case_WorkList { get; set; }
        public virtual ICollection<ADOPT_Case_Details> ADOPT_Case_Details { get; set; }
        public virtual ICollection<RACAP_OrgansationResponsible> RACAP_OrgansationResponsible { get; set; }
        public virtual ICollection<RACAP_Case_Details> RACAP_Case_Details { get; set; }
        public virtual ICollection<PCM_Case_Details> PCM_Case_Details { get; set; }
        public virtual ICollection<PCM_Previous_Involvement_Details> PCM_Previous_Involvement_Details { get; set; }
        public virtual ICollection<PCM_Recommendation> PCM_Recommendation { get; set; }
        public virtual ICollection<PCM_Victim_Details> PCM_Victim_Details { get; set; }
        public virtual ICollection<PCM_Victim_Organisation_Details> PCM_Victim_Organisation_Details { get; set; }
        public virtual ICollection<PCM_WorkList> PCM_WorkList { get; set; }
    }
}
