//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job_Position
    {
        public Job_Position()
        {
            this.Employees = new HashSet<Employee>();
            this.ACM_IDPConsultedPeople = new HashSet<ACM_IDPConsultedPeople>();
        }
    
        public int Job_Position_Id { get; set; }
        public string Description { get; set; }
        public string Source { get; set; }
        public string Definition { get; set; }
    
        public virtual ICollection<Employee> Employees { get; set; }
        public virtual ICollection<ACM_IDPConsultedPeople> ACM_IDPConsultedPeople { get; set; }
    }
}
