//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Local_Municipality
    {
        public Local_Municipality()
        {
            this.Towns = new HashSet<Town>();
            this.NISIS_Ward = new HashSet<NISIS_Ward>();
            this.apl_Organization = new HashSet<Organization>();
            this.apl_Service_Office = new HashSet<Service_Office>();
        }
    
        public int Local_Municipality_Id { get; set; }
        public int District_Municipality_Id { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Town> Towns { get; set; }
        public virtual ICollection<NISIS_Ward> NISIS_Ward { get; set; }
        public virtual District District { get; set; }
        public virtual ICollection<Organization> apl_Organization { get; set; }
        public virtual ICollection<Service_Office> apl_Service_Office { get; set; }
    }
}
