//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu_Item
    {
        public Menu_Item()
        {
            this.Sub_Menu_Items = new HashSet<Menu_Item>();
        }
    
        public int Menu_Item_Id { get; set; }
        public int Menu_Id { get; set; }
        public string Menu_Text { get; set; }
        public string Menu_Tooltip { get; set; }
        public Nullable<int> Module_Action_Id { get; set; }
        public Nullable<int> Parent_Menu_Item_Id { get; set; }
        public Nullable<int> Sort_Order { get; set; }
        public bool Is_Active { get; set; }
        public bool Is_Deleted { get; set; }
        public System.DateTime Date_Created { get; set; }
        public string Created_By { get; set; }
    
        public virtual Menu Menu { get; set; }
        public virtual ICollection<Menu_Item> Sub_Menu_Items { get; set; }
        public virtual Menu_Item Parent_Menu_Item { get; set; }
        public virtual Module_Action Module_Action { get; set; }
    }
}
