//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Module_Controller
    {
        public Module_Controller()
        {
            this.Module_Actions = new HashSet<Module_Action>();
        }
    
        public int Module_Controller_Id { get; set; }
        public int Module_Id { get; set; }
        public string Module_Controller_Name { get; set; }
    
        public virtual Module Module { get; set; }
        public virtual ICollection<Module_Action> Module_Actions { get; set; }
    }
}
