//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NISIS_Site_EA
    {
        public NISIS_Site_EA()
        {
            this.NISIS_Site_EA_Segments = new HashSet<NISIS_Site_EA_Segment>();
            this.NISIS_Profiling_Instances = new HashSet<Profiling_Instance>();
            this.NISIS_Community_Profiling_Instance = new HashSet<Community_Profiling_Instance>();
        }
    
        public int NISIS_Site_EA_Id { get; set; }
        public int NISIS_Site_Id { get; set; }
        public string EA_Code { get; set; }
        public string Community_Name { get; set; }
        public System.DateTime Date_Created { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Date_Last_Modified { get; set; }
        public string Modified_By { get; set; }
        public bool Is_Active { get; set; }
        public bool Is_Deleted { get; set; }
    
        public virtual NISIS_Site NISIS_Site { get; set; }
        public virtual ICollection<NISIS_Site_EA_Segment> NISIS_Site_EA_Segments { get; set; }
        public virtual ICollection<Profiling_Instance> NISIS_Profiling_Instances { get; set; }
        public virtual ICollection<Community_Profiling_Instance> NISIS_Community_Profiling_Instance { get; set; }
    }
}
