//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NISIS_Referral_Engine
    {
        public int NISIS_Referral_Engine_Id { get; set; }
        public int NISIS_Questionnaire_Question_Id { get; set; }
        public string NISIS_Questionnaire_Answer_Value { get; set; }
        public int NISIS_Service_Id { get; set; }
    
        public virtual Questionnaire_Question NISIS_Questionnaire_Question { get; set; }
        public virtual NISIS_Service NISIS_Service { get; set; }
    }
}
