//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NISIS_Site_EA_Segment
    {
        public NISIS_Site_EA_Segment()
        {
            this.NISIS_Listings = new HashSet<NISIS_Listing>();
        }
    
        public int Segment_Id { get; set; }
        public int NISIS_Site_EA_Id { get; set; }
        public int Segment_Number { get; set; }
        public string Boundary_Description { get; set; }
        public string Listing_Start_Point_Description { get; set; }
        public string Listing_Route { get; set; }
        public System.DateTime Date_Created { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Date_Last_Modified { get; set; }
        public string Modified_By { get; set; }
        public bool Is_Active { get; set; }
        public bool Is_Deleted { get; set; }
    
        public virtual NISIS_Site_EA NISIS_Site_EA { get; set; }
        public virtual ICollection<NISIS_Listing> NISIS_Listings { get; set; }
    }
}
