//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NISIS_Service
    {
        public NISIS_Service()
        {
            this.NISIS_Profiling_Instance_Referrals = new HashSet<NISIS_Profiling_Instance_Referral>();
            this.NISIS_Referral_Engine = new HashSet<NISIS_Referral_Engine>();
        }
    
        public int Service_Id { get; set; }
        public int Service_Category_Id { get; set; }
        public string Description { get; set; }
        public string Source { get; set; }
        public string Definition { get; set; }
    
        public virtual ICollection<NISIS_Profiling_Instance_Referral> NISIS_Profiling_Instance_Referrals { get; set; }
        public virtual ICollection<NISIS_Referral_Engine> NISIS_Referral_Engine { get; set; }
        public virtual NISIS_Service_Category NISIS_Service_Category { get; set; }
    }
}
