//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NISIS_Profiling_Instance_Referral
    {
        public int NISIS_Household_Referral_Id { get; set; }
        public int Profiling_Instance_Id { get; set; }
        public int Referral_Source_Type_Id { get; set; }
        public Nullable<int> Household_Member_Id { get; set; }
        public Nullable<int> Service_Id { get; set; }
        public Nullable<int> Service_Status_Id { get; set; }
        public Nullable<int> Referral_Priority_Id { get; set; }
        public string Supporting_Comments { get; set; }
        public Nullable<int> Responsible_Person_Id { get; set; }
        public Nullable<int> Owner_Organization_Id { get; set; }
        public Nullable<int> Organization_Facility_Id { get; set; }
        public Nullable<System.DateTime> SLA_Delivery_Date { get; set; }
        public Nullable<int> External_Verification_Status_Id { get; set; }
        public Nullable<System.DateTime> Delivery_Date { get; set; }
        public Nullable<System.DateTime> Expected_Delivery_Date { get; set; }
        public string Referral_Reason { get; set; }
        public bool Is_Active { get; set; }
        public bool Is_Deleted { get; set; }
        public System.DateTime Date_Created { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Date_Last_Modified { get; set; }
        public string Modified_By { get; set; }
    
        public virtual NISIS_External_Verification_Status NISIS_External_Verification_Status { get; set; }
        public virtual NISIS_Owner_Organization NISIS_Owner_Organization { get; set; }
        public virtual Profiling_Instance NISIS_Profiling_Instance { get; set; }
        public virtual NISIS_Referral_Priority NISIS_Referral_Priority { get; set; }
        public virtual NISIS_Referral_Source_Type NISIS_Referral_Source_Type { get; set; }
        public virtual NISIS_Service NISIS_Service { get; set; }
        public virtual NISIS_Service_Status NISIS_Service_Status { get; set; }
    }
}
