//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NISIS_Listing
    {
        public int NISIS_Listing_Id { get; set; }
        public int Segment_Id { get; set; }
        public Nullable<int> Record_Number { get; set; }
        public Nullable<int> Dwelling_Unit_Number { get; set; }
        public Nullable<int> Listing_Method_Id { get; set; }
        public Nullable<int> Captured_By_User_Id { get; set; }
        public string Household_Head_First_Name { get; set; }
        public string Household_Head_Last_Name { get; set; }
        public string Household_Head_Middle_Name { get; set; }
        public string Street_Address { get; set; }
        public string House_Other_Number { get; set; }
        public Nullable<int> Structure_Type_Id { get; set; }
        public string Structure_Description { get; set; }
        public string Queries_or_Comments { get; set; }
        public Nullable<int> QA_Status_Item_Id { get; set; }
        public string Created_By { get; set; }
        public System.DateTime Created_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public bool Is_Active { get; set; }
        public bool Is_Deleted { get; set; }
    
        public virtual Structure_Type Structure_Type { get; set; }
        public virtual NISIS_Listing_Method NISIS_Listing_Method { get; set; }
        public virtual NISIS_Site_EA_Segment NISIS_Site_EA_Segment { get; set; }
        public virtual NISIS_QA_Status_Item NISIS_QA_Status_Item { get; set; }
    }
}
