//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NISIS_Referral_Priority
    {
        public NISIS_Referral_Priority()
        {
            this.NISIS_Profiling_Instance_Referrals = new HashSet<NISIS_Profiling_Instance_Referral>();
        }
    
        public int Referral_Priority_Id { get; set; }
        public string Description { get; set; }
        public string Source { get; set; }
        public string Definition { get; set; }
    
        public virtual ICollection<NISIS_Profiling_Instance_Referral> NISIS_Profiling_Instance_Referrals { get; set; }
    }
}
