//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NISIS_Profiling_Method
    {
        public NISIS_Profiling_Method()
        {
            this.NISIS_Sites = new HashSet<NISIS_Site>();
            this.NISIS_Profiling_Instances = new HashSet<Profiling_Instance>();
        }
    
        public int NISIS_Profiling_Method_Id { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<NISIS_Site> NISIS_Sites { get; set; }
        public virtual ICollection<Profiling_Instance> NISIS_Profiling_Instances { get; set; }
    }
}
