//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NISIS_Programme_Status
    {
        public NISIS_Programme_Status()
        {
            this.Registered_Programme_Status_Site = new HashSet<NISIS_Site>();
        }
    
        public int Programme_Status_Item_Id { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<NISIS_Site> Registered_Programme_Status_Site { get; set; }
    }
}
