//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NISIS_Owner_Organization
    {
        public NISIS_Owner_Organization()
        {
            this.NISIS_Profiling_Instance_Referrals = new HashSet<NISIS_Profiling_Instance_Referral>();
            this.NISIS_Organization_Facilities = new HashSet<NISIS_Organization_Facility>();
        }
    
        public int Owner_Organization_Id { get; set; }
        public string Description { get; set; }
        public string Source { get; set; }
        public string Definition { get; set; }
        public Nullable<int> Owner_Organization_Type_Id { get; set; }
        public Nullable<int> Province_Id { get; set; }
        public Nullable<int> Vote_Code { get; set; }
        public bool Is_National_Department { get; set; }
    
        public virtual ICollection<NISIS_Profiling_Instance_Referral> NISIS_Profiling_Instance_Referrals { get; set; }
        public virtual ICollection<NISIS_Organization_Facility> NISIS_Organization_Facilities { get; set; }
    }
}
