//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Office_Type
    {
        public Office_Type()
        {
            this.Action_Taken_Items = new HashSet<Action_Taken>();
            this.Case_Note_Items = new HashSet<Case_Note>();
        }
    
        public int Office_Type_Id { get; set; }
        public string Description { get; set; }
        public string Source { get; set; }
        public string Definition { get; set; }
    
        public virtual ICollection<Action_Taken> Action_Taken_Items { get; set; }
        public virtual ICollection<Case_Note> Case_Note_Items { get; set; }
    }
}
