//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paypoint
    {
        public Paypoint()
        {
            this.Employees = new HashSet<Employee>();
        }
    
        public int Paypoint_Id { get; set; }
        public Nullable<int> District_Id { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Employee> Employees { get; set; }
        public virtual District District { get; set; }
    }
}
