//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCM_CYCA_Request_For_Space
    {
        public long Request_For_Space_ID { get; set; }
        public Nullable<int> PCM_Case_Id { get; set; }
        public Nullable<int> Requesting_Employer_Id { get; set; }
        public Nullable<int> PCM_Offence_Id { get; set; }
        public string Req_Subject { get; set; }
        public Nullable<int> Province_Id { get; set; }
        public Nullable<int> Court_Id { get; set; }
        public Nullable<System.DateTime> Date_Recieved { get; set; }
        public Nullable<System.DateTime> Time_Recieved { get; set; }
        public string Req_Comments { get; set; }
        public Nullable<int> Facility_ID { get; set; }
        public string Approved_Comments { get; set; }
        public Nullable<System.DateTime> Reply_Date { get; set; }
        public Nullable<System.DateTime> Reply_Time { get; set; }
        public Nullable<int> Request_Status { get; set; }
        public string Request_Status_Comments { get; set; }
        public string Request_Open_Close { get; set; }
        public Nullable<System.DateTime> Date_Closed { get; set; }
        public Nullable<int> Employee_ID_Attended_Req { get; set; }
        public Nullable<int> Created_By { get; set; }
        public Nullable<System.DateTime> Date_Created { get; set; }
        public Nullable<int> Modified_By { get; set; }
        public Nullable<System.DateTime> Date_Modified { get; set; }
    
        public virtual PCM_Case_Details PCM_Case_Details { get; set; }
    }
}
