//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCM_EndPoint_PO_Inbox
    {
        public int End_Point_POD_Id { get; set; }
        public Nullable<int> CaseInformationID { get; set; }
        public Nullable<int> Person_Id { get; set; }
        public Nullable<int> NotificacationId { get; set; }
        public Nullable<System.DateTime> Date_Recieved { get; set; }
        public Nullable<int> Endpoint_Record_Status_Id { get; set; }
        public Nullable<int> Case_Allocated_To { get; set; }
        public Nullable<int> Allocated_ByS { get; set; }
        public Nullable<int> Created_By { get; set; }
        public Nullable<System.DateTime> Date_Created { get; set; }
        public Nullable<int> Modified_By { get; set; }
        public Nullable<System.DateTime> Date_Modified { get; set; }
    }
}
