//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCM_Recommendation
    {
        public PCM_Recommendation()
        {
            this.PCM_Childrens_Court = new HashSet<PCM_Childrens_Court>();
            this.PCM_Conversion_Recommendation = new HashSet<PCM_Conversion_Recommendation>();
            this.PCM_Diversion_Recommendation = new HashSet<PCM_Diversion_Recommendation>();
            this.PCM_Formal_Court_Recommendation = new HashSet<PCM_Formal_Court_Recommendation>();
            this.PCM_Home_Based_Recommendation = new HashSet<PCM_Home_Based_Recommendation>();
        }
    
        public int Recommendation_Id { get; set; }
        public Nullable<int> Recommendation_Type_Id { get; set; }
        public Nullable<int> Placement_Type_Id { get; set; }
        public string Comments_For_Recommendation { get; set; }
        public Nullable<int> Created_By { get; set; }
        public Nullable<System.DateTime> Date_Created { get; set; }
        public Nullable<int> Modified_By { get; set; }
        public Nullable<System.DateTime> Date_Modified { get; set; }
        public Nullable<int> Intake_Assessment_Id { get; set; }
    
        public virtual Intake_Assessment int_Intake_Assessment { get; set; }
        public virtual ICollection<PCM_Childrens_Court> PCM_Childrens_Court { get; set; }
        public virtual ICollection<PCM_Conversion_Recommendation> PCM_Conversion_Recommendation { get; set; }
        public virtual ICollection<PCM_Diversion_Recommendation> PCM_Diversion_Recommendation { get; set; }
        public virtual ICollection<PCM_Formal_Court_Recommendation> PCM_Formal_Court_Recommendation { get; set; }
        public virtual ICollection<PCM_Home_Based_Recommendation> PCM_Home_Based_Recommendation { get; set; }
        public virtual PCM_Assessment_Register PCM_Assessment_Register { get; set; }
    }
}
