//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCM_Referral_Types
    {
        public int Category_Referrals_Id { get; set; }
        public Nullable<int> Referrals_Id { get; set; }
        public Nullable<int> Type_Referral_Id { get; set; }
        public Nullable<int> Intake_Assessment_Id { get; set; }
        public Nullable<int> Client_Employee_Details_ID { get; set; }
        public Nullable<System.DateTime> Refferal_Date { get; set; }
        public Nullable<System.DateTime> Period_From { get; set; }
        public Nullable<System.DateTime> Period_To { get; set; }
        public string Progress_Report { get; set; }
        public Nullable<int> Employee_Id_Copy_To { get; set; }
        public Nullable<int> Created_By { get; set; }
        public Nullable<System.DateTime> Date_Created { get; set; }
        public Nullable<int> Modified_By { get; set; }
        public Nullable<System.DateTime> Date_Modified { get; set; }
    }
}
