//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCM_D_Session_Outcome
    {
        public int DSession_Id { get; set; }
        public Nullable<int> Intake_Assessment_Id { get; set; }
        public string Current_Module_Attended { get; set; }
        public string Session_Attend { get; set; }
        public string Session_Date { get; set; }
        public string Name_of_the_Facilitator { get; set; }
        public string Name_of_Co_Facilitator { get; set; }
        public string Process_Notes { get; set; }
        public string Next_Session_Date { get; set; }
        public string Compliance { get; set; }
    }
}
