//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCM_Diversion_File
    {
        public int File_Id { get; set; }
        public Nullable<int> Intake_Assessment_Id { get; set; }
        public string Module_Name { get; set; }
        public string Description { get; set; }
        public string File_Doc { get; set; }
        public string File_Name { get; set; }
    }
}
