//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCM_Case_Details
    {
        public PCM_Case_Details()
        {
            this.PCM_CYCA_Request_For_Space = new HashSet<PCM_CYCA_Request_For_Space>();
            this.PCM_Preliminary_Details = new HashSet<PCM_Preliminary_Details>();
            this.PCM_Referrals = new HashSet<PCM_Referrals>();
        }
    
        public int PCM_Case_Id { get; set; }
        public Nullable<int> Intake_Assessment_Id { get; set; }
        public Nullable<int> Client_Module_Id { get; set; }
        public Nullable<System.DateTime> Date_Arrested { get; set; }
        public Nullable<System.DateTime> Time_Arrested { get; set; }
        public string Arresting_Officer_Name { get; set; }
        public string Investigate_Officer_Name { get; set; }
        public Nullable<int> SAPS_Station_Id { get; set; }
        public Nullable<int> SAPS_Info_Id { get; set; }
        public Nullable<int> Detention_Place_Id { get; set; }
        public Nullable<int> Court_id { get; set; }
        public string CAS_No { get; set; }
        public Nullable<System.DateTime> First_Appear_Date { get; set; }
        public string Num_Of_Days_Custody { get; set; }
        public Nullable<int> Has_Legal_Representitive { get; set; }
        public string Name_Oflegal_Representitive { get; set; }
        public bool Is_Active { get; set; }
        public bool Is_Deleted { get; set; }
        public Nullable<int> Created_By { get; set; }
        public Nullable<System.DateTime> Date_Created { get; set; }
        public Nullable<int> Modified_By { get; set; }
        public Nullable<System.DateTime> Date_Modified { get; set; }
    
        public virtual Court apl_Court { get; set; }
        public virtual SAPS_Official apl_SAPS_Official { get; set; }
        public virtual SAPS_Station apl_SAPS_Station { get; set; }
        public virtual int_Client_Module_Registration int_Client_Module_Registration { get; set; }
        public virtual Intake_Assessment int_Intake_Assessment { get; set; }
        public virtual ICollection<PCM_CYCA_Request_For_Space> PCM_CYCA_Request_For_Space { get; set; }
        public virtual ICollection<PCM_Preliminary_Details> PCM_Preliminary_Details { get; set; }
        public virtual ICollection<PCM_Referrals> PCM_Referrals { get; set; }
    }
}
