//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCM_Offence_Details
    {
        public PCM_Offence_Details()
        {
            this.PCM_Preliminary_Details = new HashSet<PCM_Preliminary_Details>();
        }
    
        public int PCM_Offence_Id { get; set; }
        public Nullable<int> PCM_Case_Id { get; set; }
        public Nullable<int> Intake_Assessment_Id { get; set; }
        public Nullable<int> Offence_Type_Id { get; set; }
        public Nullable<int> Offence_Category_Id { get; set; }
        public Nullable<int> Offence_Schedule_Id { get; set; }
        public string Offence_Circumstance { get; set; }
        public string Value_Of_Goods { get; set; }
        public string Value_Recovered { get; set; }
        public string IsChild_Responsible { get; set; }
        public string Responsibility_Details { get; set; }
        public Nullable<int> Created_By { get; set; }
        public Nullable<System.DateTime> Date_Created { get; set; }
        public Nullable<int> Modified_By { get; set; }
        public Nullable<System.DateTime> Date_Modified { get; set; }
    
        public virtual Offence_Category apl_Offence_Category { get; set; }
        public virtual apl_Offence_Type apl_Offence_Type { get; set; }
        public virtual PCM_Offence_Details PCM_Offence_Details1 { get; set; }
        public virtual PCM_Offence_Details PCM_Offence_Details2 { get; set; }
        public virtual ICollection<PCM_Preliminary_Details> PCM_Preliminary_Details { get; set; }
    }
}
