//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCM_Diversion_SP
    {
        public int S_P_Id { get; set; }
        public Nullable<int> Services_Provider_Id { get; set; }
        public Nullable<int> Intake_Assessment_Id { get; set; }
        public Nullable<int> Province_Id { get; set; }
    
        public virtual PCM_D_ServicesProvider PCM_D_ServicesProvider { get; set; }
    }
}
