//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCM_Development_Assessment
    {
        public int Development_Id { get; set; }
        public Nullable<int> Intake_Assessment_Id { get; set; }
        public string Belonging { get; set; }
        public string Mastery { get; set; }
        public string Independence { get; set; }
        public string Generosity { get; set; }
        public string Evaluation { get; set; }
        public Nullable<int> Created_By { get; set; }
        public Nullable<int> Modified_By { get; set; }
        public Nullable<System.DateTime> Date_Created { get; set; }
        public Nullable<System.DateTime> Date_Modified { get; set; }
    }
}
