//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCM_HB
    {
        public PCM_HB()
        {
            this.PCM_HB_Supervision = new HashSet<PCM_HB_Supervision>();
        }
    
        public int HBS_Supervisor_Id { get; set; }
        public string HBS_Supervisor { get; set; }
    
        public virtual ICollection<PCM_HB_Supervision> PCM_HB_Supervision { get; set; }
    }
}
