//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCM_D_ServicesProvider
    {
        public PCM_D_ServicesProvider()
        {
            this.PCM_Diversion = new HashSet<PCM_Diversion>();
            this.PCM_Diversion_SP = new HashSet<PCM_Diversion_SP>();
        }
    
        public int Services_Provider_Id { get; set; }
        public string Services_Provider_Name { get; set; }
        public string Services_Provider_Status { get; set; }
        public Nullable<int> Province_Id { get; set; }
    
        public virtual Province apl_Province { get; set; }
        public virtual ICollection<PCM_Diversion> PCM_Diversion { get; set; }
        public virtual ICollection<PCM_Diversion_SP> PCM_Diversion_SP { get; set; }
    }
}
