//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCM_General_Details
    {
        public int General_Details_Id { get; set; }
        public Nullable<int> Intake_Assessment_Id { get; set; }
        public string Consulted_Sources { get; set; }
        public string Trace_Efforts { get; set; }
        public Nullable<System.DateTime> Assessment_Date { get; set; }
        public Nullable<System.DateTime> Assessment_Time { get; set; }
        public string Additional_Info { get; set; }
        public Nullable<int> Created_By { get; set; }
        public Nullable<int> Modified_By { get; set; }
        public Nullable<System.DateTime> Date_Created { get; set; }
        public Nullable<System.DateTime> Date_Modified { get; set; }
    }
}
