//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCM_Victim_Organisation_Details
    {
        public int Victim_Organisation_Id { get; set; }
        public Nullable<int> Intake_Assessment_Id { get; set; }
        public string Organisation_Name { get; set; }
        public string Contact_Person_First_Name { get; set; }
        public string Contact_Person_Last_Name { get; set; }
        public string Telephone { get; set; }
        public string Cell_No { get; set; }
        public string Interventionservice_referrals { get; set; }
        public string Other_Contacts { get; set; }
        public string Contact_Person_Occupation { get; set; }
        public string Address_Line_1 { get; set; }
        public string Address_Line_2 { get; set; }
        public Nullable<int> Town_Id { get; set; }
        public string Postal_Code { get; set; }
        public Nullable<int> Created_By { get; set; }
        public Nullable<System.DateTime> Date_Created { get; set; }
        public Nullable<int> Modified_By { get; set; }
        public Nullable<System.DateTime> Date_Modified { get; set; }
    
        public virtual Intake_Assessment int_Intake_Assessment { get; set; }
    }
}
