//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCM_Victim_Details
    {
        public int Victim_Id { get; set; }
        public Nullable<int> Intake_Assessment_Id { get; set; }
        public string IsVictimIndividual { get; set; }
        public Nullable<int> Person_Id { get; set; }
        public string Victim_Occupation { get; set; }
        public string Victim_Care_Giver_Names { get; set; }
        public string Address_Line_1 { get; set; }
        public string Address_Line_2 { get; set; }
        public Nullable<int> Town_Id { get; set; }
        public string Postal_Code { get; set; }
        public Nullable<int> Created_By { get; set; }
        public Nullable<System.DateTime> Date_Created { get; set; }
        public Nullable<int> Modified_By { get; set; }
        public Nullable<System.DateTime> Date_Modified { get; set; }
    
        public virtual Intake_Assessment int_Intake_Assessment { get; set; }
    }
}
