//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCM_Socio_Economy
    {
        public int Socio_Economy_id { get; set; }
        public Nullable<int> Intake_Assessment_Id { get; set; }
        public string Family_Background_Comment { get; set; }
        public string Finance_Work_Record { get; set; }
        public string Housing { get; set; }
        public string Social_Circumsances { get; set; }
        public string Previous_Intervention { get; set; }
        public string Inter_Personal_Relationship { get; set; }
        public string Peer_Presure { get; set; }
        public string Substance_Abuse { get; set; }
        public string Religious_Involve { get; set; }
        public string Child_Behavior { get; set; }
        public string Other { get; set; }
        public Nullable<int> Created_By { get; set; }
        public Nullable<System.DateTime> Date_Created { get; set; }
        public Nullable<int> Modified_By { get; set; }
        public Nullable<System.DateTime> Date_Modified { get; set; }
    }
}
