//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCM_Childrens_CourtOutcome_CaseStatus
    {
        public int CourtOutcome_CaseStatus_ID { get; set; }
        public string CourtOutcome_CaseStatus { get; set; }
    }
}
