//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCM_HB_VistationOutcome
    {
        public int HB_Visitaion_Outcome_Id { get; set; }
        public Nullable<int> HomeBasedSupervision_Id { get; set; }
        public Nullable<int> Intake_Assessment_Id { get; set; }
        public string Conatact_Number { get; set; }
        public string Process_Notes { get; set; }
        public string Visitaion_Register { get; set; }
        public Nullable<int> Compliance_Id { get; set; }
    
        public virtual PCM_HB_Supervision PCM_HB_Supervision { get; set; }
    }
}
