//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCM_Diversion_Outcomes
    {
        public int Diversion_Outcome_Id { get; set; }
        public Nullable<int> Diversion_Id { get; set; }
        public Nullable<System.DateTime> Date_Attended_Programme { get; set; }
        public Nullable<int> Session_Activity_Id { get; set; }
        public Nullable<System.DateTime> Start_Time { get; set; }
        public Nullable<System.DateTime> End_Time { get; set; }
        public string Outcome_Details { get; set; }
    
        public virtual PCM_Diversion PCM_Diversion { get; set; }
    }
}
