//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCM_Childrens_Court
    {
        public PCM_Childrens_Court()
        {
            this.PCM_Childrens_Court_Outcome = new HashSet<PCM_Childrens_Court_Outcome>();
        }
    
        public int Children_Court_Id { get; set; }
        public Nullable<int> PCM_Recommendation_Id { get; set; }
        public Nullable<System.DateTime> Court_Expiry_Date { get; set; }
        public Nullable<System.DateTime> Prelim_Enquiry_Date { get; set; }
        public string Child_Need_Care { get; set; }
        public string Alternative_Placement { get; set; }
        public string Substance_Abuse_Treat { get; set; }
        public Nullable<System.DateTime> Referral_Date { get; set; }
        public string Case_Manager { get; set; }
        public string Service_Provider { get; set; }
        public Nullable<int> Intake_Assessment_Id { get; set; }
    
        public virtual ICollection<PCM_Childrens_Court_Outcome> PCM_Childrens_Court_Outcome { get; set; }
        public virtual PCM_Recommendation PCM_Recommendation { get; set; }
    }
}
