//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCM_HB_Supervision
    {
        public PCM_HB_Supervision()
        {
            this.PCM_HB_CourtOutcome = new HashSet<PCM_HB_CourtOutcome>();
            this.PCM_HB_VistationOutcome = new HashSet<PCM_HB_VistationOutcome>();
        }
    
        public int HomeBasedSupervision_Id { get; set; }
        public Nullable<int> Intake_Assessment_Id { get; set; }
        public Nullable<int> Outcome_Id { get; set; }
        public Nullable<int> FormalCourtOutcome_Id { get; set; }
        public Nullable<int> PCM_Preliminary_Id { get; set; }
        public Nullable<int> Court_Type_Id { get; set; }
        public Nullable<int> Conditions_Id { get; set; }
        public string Visitation_Period { get; set; }
        public Nullable<int> Number_of_Visit { get; set; }
        public Nullable<System.DateTime> Placement_Date { get; set; }
        public Nullable<int> HBS_Supervisor_Id { get; set; }
        public string Placement_Confirmed { get; set; }
    
        public virtual PCM_HB PCM_HB { get; set; }
        public virtual ICollection<PCM_HB_CourtOutcome> PCM_HB_CourtOutcome { get; set; }
        public virtual ICollection<PCM_HB_VistationOutcome> PCM_HB_VistationOutcome { get; set; }
    }
}
