//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCM_D_Diversion_Outcome
    {
        public int Diversion_Outotcome_Id { get; set; }
        public Nullable<int> Intake_Assessment_Id { get; set; }
        public Nullable<System.DateTime> Court_Date { get; set; }
        public string Remand { get; set; }
        public string Reason_Remand { get; set; }
        public Nullable<System.DateTime> Next_Court_Date { get; set; }
        public string Court_Outcome { get; set; }
        public string Case_Status { get; set; }
    }
}
