//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCM_Previous_Involvement_Details
    {
        public int Involvement_Id { get; set; }
        public Nullable<int> Intake_Assessment_Id { get; set; }
        public string Previous_Involved { get; set; }
        public string IsArrest { get; set; }
        public Nullable<System.DateTime> Arrest_Date { get; set; }
        public Nullable<int> Offence_Category_Id { get; set; }
        public string Sentence_Outcomes { get; set; }
        public string IsConvicted { get; set; }
        public Nullable<System.DateTime> Conviction_Date { get; set; }
        public string IsEscape { get; set; }
        public Nullable<System.DateTime> Escapes_Date { get; set; }
        public Nullable<System.DateTime> Escape_Time { get; set; }
        public Nullable<int> When_Escaped_Id { get; set; }
        public string Place_Of_Escape { get; set; }
        public Nullable<int> Created_By { get; set; }
        public Nullable<System.DateTime> Date_Created { get; set; }
        public Nullable<int> Modified_By { get; set; }
        public Nullable<System.DateTime> Date_Modified { get; set; }
    
        public virtual Offence_Category apl_Offence_Category { get; set; }
        public virtual Intake_Assessment int_Intake_Assessment { get; set; }
    }
}
