//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCM_Facility_Space_Inbox_ReqOutBox
    {
        public long Request_Id { get; set; }
        public Nullable<int> Sent_By { get; set; }
        public Nullable<int> Intake_Assessment_Id { get; set; }
        public string Request_Subject { get; set; }
        public Nullable<int> Province_Id { get; set; }
        public Nullable<System.DateTime> Date_Recieved { get; set; }
        public string Time_Recieved { get; set; }
        public string Request_Comments { get; set; }
        public Nullable<int> Facility_Id { get; set; }
        public string Approved_Comments { get; set; }
        public Nullable<System.DateTime> Reply_Date { get; set; }
        public Nullable<System.DateTime> Reply_Time { get; set; }
        public Nullable<int> Request_Status_Id { get; set; }
        public string Request_Status_Comments { get; set; }
        public string Request_Open_Close { get; set; }
        public Nullable<System.DateTime> Date_Closed { get; set; }
        public Nullable<int> Admission_Type_Id { get; set; }
        public Nullable<int> Created_By { get; set; }
        public Nullable<System.DateTime> Date_Created { get; set; }
        public Nullable<int> Modified_By { get; set; }
        public Nullable<System.DateTime> Date_Modified { get; set; }
    }
}
