//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCM_D_Programme
    {
        public int Programme_Id { get; set; }
        public Nullable<int> Services_Provider_Id { get; set; }
        public string Programme_name { get; set; }
        public string Programme_Status { get; set; }
        public Nullable<System.DateTime> Programme_Expiry_Date { get; set; }
    }
}
