//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person_Employment
    {
        public int Person_Employment_Id { get; set; }
        public int Person_Id { get; set; }
        public Nullable<int> Nature_Of_Employment_Id { get; set; }
        public string Occupation { get; set; }
        public Nullable<int> Income_Range_Id { get; set; }
        public System.DateTime Date_Created { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Date_Last_Modified { get; set; }
        public string Modified_By { get; set; }
        public bool Is_Active { get; set; }
        public bool Is_Deleted { get; set; }
        public string NameOfEmployer { get; set; }
    
        public virtual Income_Range apl_Income_Range { get; set; }
        public virtual Nature_of_Employment apl_Nature_of_Employment { get; set; }
        public virtual Person int_Person { get; set; }
    }
}
