//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person_Image
    {
        public int Person_Image_Id { get; set; }
        public int Person_Id { get; set; }
        public int Image_Type_Id { get; set; }
        public string Image_Filename { get; set; }
        public byte[] Image_Content { get; set; }
        public string Image_Content_Type { get; set; }
        public System.DateTime Date_Created { get; set; }
        public string Created_By { get; set; }
    
        public virtual Image_Type Image_Type { get; set; }
        public virtual Person Person { get; set; }
    }
}
