//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public Person()
        {
            this.Clients = new HashSet<Client>();
            this.Reception_Registers = new HashSet<Reception_Register>();
            this.Person_Education_Items = new HashSet<Person_Education>();
            this.Allergies = new HashSet<Allergy>();
            this.Chronic_Illnesses = new HashSet<Chronic_Illness>();
            this.Addresses = new HashSet<Address>();
            this.Client_Adopted_Children = new HashSet<Client_Adoptive_Parent>();
            this.Client_Biological_Children = new HashSet<Client_Biological_Parent>();
            this.Client_Foster_Children = new HashSet<Client_Foster_Parent>();
            this.Client_Family_Members = new HashSet<Client_Family_Member>();
            this.Client_CareGiverFor_Persons = new HashSet<Client_CareGiver>();
            this.Alleged_Offenders = new HashSet<Alleged_Offender>();
            this.CPR_First_Reporters = new HashSet<CPR_First_Reporter>();
            this.Images = new HashSet<Person_Image>();
            this.ACM_InformationSources = new HashSet<ACM_InformationSources>();
            this.ACM_ParentCaregiversAssessed = new HashSet<ACM_ParentCaregiversAssessed>();
            this.NISIS_Profiling_Participants = new HashSet<Profiling_Participant>();
            this.ACM_AraSourcesOfInformation = new HashSet<ACM_AraSourcesOfInformation>();
            this.ACM_ParentsGuardiansAssentingToSurgicalOperation = new HashSet<ACM_ParentsGuardiansAssentingToSurgicalOperation>();
            this.CPR_Correspondence = new HashSet<CPR_Correspondence>();
            this.ACM_InterviewedPersons = new HashSet<ACM_InterviewedPersons>();
            this.ACM_IDPConsultedPeople = new HashSet<ACM_IDPConsultedPeople>();
            this.ACM_IDPPeopleWhoHadParentalResponsibilities = new HashSet<ACM_IDPPeopleWhoHadParentalResponsibilities>();
            this.ACM_IDPMeetingPersonPresence = new HashSet<ACM_IDPMeetingPersonPresence>();
            this.CPR_Informant = new HashSet<CPR_Informant>();
            this.CPR_Unsuitability = new HashSet<CPR_Unsuitability>();
            this.int_Client_Prospective_Adoptive_Parent = new HashSet<int_Client_Prospective_Adoptive_Parent>();
            this.int_Disability_Selection = new HashSet<int_Disability_Selection>();
            this.int_Client_ProspectiveAdoptiveParents = new HashSet<int_Client_ProspectiveAdoptiveParents>();
            this.apl_Decease = new HashSet<apl_Decease>();
            this.int_Person_Employment = new HashSet<Person_Employment>();
        }
    
        public int Person_Id { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Known_As { get; set; }
        public Nullable<int> Identification_Type_Id { get; set; }
        public string Identification_Number { get; set; }
        public bool Is_Piva_Validated { get; set; }
        public string Piva_Transaction_Id { get; set; }
        public Nullable<System.DateTime> Date_Of_Birth { get; set; }
        public Nullable<int> Age { get; set; }
        public bool Is_Estimated_Age { get; set; }
        public Nullable<int> Language_Id { get; set; }
        public Nullable<int> Gender_Id { get; set; }
        public Nullable<int> Marital_Status_Id { get; set; }
        public Nullable<int> Preferred_Contact_Type_Id { get; set; }
        public Nullable<int> Religion_Id { get; set; }
        public string Phone_Number { get; set; }
        public string Mobile_Phone_Number { get; set; }
        public string Email_Address { get; set; }
        public Nullable<int> Population_Group_Id { get; set; }
        public Nullable<int> Nationality_Id { get; set; }
        public Nullable<int> Disability_Type_Id { get; set; }
        public System.DateTime Date_Created { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Date_Last_Modified { get; set; }
        public string Modified_By { get; set; }
        public bool Is_Active { get; set; }
        public bool Is_Deleted { get; set; }
        public Nullable<int> Sexual_Orientation_Id { get; set; }
        public Nullable<int> Citizenship_Id { get; set; }
    
        public virtual Gender Gender { get; set; }
        public virtual ICollection<Client> Clients { get; set; }
        public virtual ICollection<Reception_Register> Reception_Registers { get; set; }
        public virtual Disability Disability { get; set; }
        public virtual Identification_Type Identification_Type { get; set; }
        public virtual Nationality Nationality { get; set; }
        public virtual Population_Group Population_Group { get; set; }
        public virtual Language Language { get; set; }
        public virtual Preferred_Contact_Type Preferred_Contact_Type { get; set; }
        public virtual Marital_Status Marital_Status { get; set; }
        public virtual Religion Religion { get; set; }
        public virtual ICollection<Person_Education> Person_Education_Items { get; set; }
        public virtual ICollection<Allergy> Allergies { get; set; }
        public virtual ICollection<Chronic_Illness> Chronic_Illnesses { get; set; }
        public virtual ICollection<Address> Addresses { get; set; }
        public virtual ICollection<Client_Adoptive_Parent> Client_Adopted_Children { get; set; }
        public virtual ICollection<Client_Biological_Parent> Client_Biological_Children { get; set; }
        public virtual ICollection<Client_Foster_Parent> Client_Foster_Children { get; set; }
        public virtual ICollection<Client_Family_Member> Client_Family_Members { get; set; }
        public virtual ICollection<Client_CareGiver> Client_CareGiverFor_Persons { get; set; }
        public virtual ICollection<Alleged_Offender> Alleged_Offenders { get; set; }
        public virtual ICollection<CPR_First_Reporter> CPR_First_Reporters { get; set; }
        public virtual ICollection<Person_Image> Images { get; set; }
        public virtual ICollection<ACM_InformationSources> ACM_InformationSources { get; set; }
        public virtual ICollection<ACM_ParentCaregiversAssessed> ACM_ParentCaregiversAssessed { get; set; }
        public virtual ICollection<Profiling_Participant> NISIS_Profiling_Participants { get; set; }
        public virtual ICollection<ACM_AraSourcesOfInformation> ACM_AraSourcesOfInformation { get; set; }
        public virtual ICollection<ACM_ParentsGuardiansAssentingToSurgicalOperation> ACM_ParentsGuardiansAssentingToSurgicalOperation { get; set; }
        public virtual ICollection<CPR_Correspondence> CPR_Correspondence { get; set; }
        public virtual ICollection<ACM_InterviewedPersons> ACM_InterviewedPersons { get; set; }
        public virtual apl_Contact_Type apl_Contact_Type { get; set; }
        public virtual ICollection<ACM_IDPConsultedPeople> ACM_IDPConsultedPeople { get; set; }
        public virtual ICollection<ACM_IDPPeopleWhoHadParentalResponsibilities> ACM_IDPPeopleWhoHadParentalResponsibilities { get; set; }
        public virtual ICollection<ACM_IDPMeetingPersonPresence> ACM_IDPMeetingPersonPresence { get; set; }
        public virtual ICollection<CPR_Informant> CPR_Informant { get; set; }
        public virtual ICollection<CPR_Unsuitability> CPR_Unsuitability { get; set; }
        public virtual ICollection<int_Client_Prospective_Adoptive_Parent> int_Client_Prospective_Adoptive_Parent { get; set; }
        public virtual ICollection<int_Disability_Selection> int_Disability_Selection { get; set; }
        public virtual ICollection<int_Client_ProspectiveAdoptiveParents> int_Client_ProspectiveAdoptiveParents { get; set; }
        public virtual VEP_Sexual_Orientation VEP_Sexual_Orientation { get; set; }
        public virtual apl_Citizenship apl_Citizenship { get; set; }
        public virtual ICollection<apl_Decease> apl_Decease { get; set; }
        public virtual ICollection<Person_Employment> int_Person_Employment { get; set; }
    }
}
