//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Problem_Sub_Category
    {
        public Problem_Sub_Category()
        {
            this.Intake_Assessments = new HashSet<Intake_Assessment>();
        }
    
        public int Problem_Sub_Category_Id { get; set; }
        public int Problem_Category_Id { get; set; }
        public Nullable<int> Module_Id { get; set; }
        public string Description { get; set; }
        public string Source { get; set; }
        public string Definition { get; set; }
    
        public virtual Problem_Category Problem_Category { get; set; }
        public virtual ICollection<Intake_Assessment> Intake_Assessments { get; set; }
    }
}
