//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Problem_Category
    {
        public Problem_Category()
        {
            this.Problem_Sub_Categories = new HashSet<Problem_Sub_Category>();
        }
    
        public int Problem_Category_Id { get; set; }
        public string Description { get; set; }
        public string Source { get; set; }
        public string Definition { get; set; }
    
        public virtual ICollection<Problem_Sub_Category> Problem_Sub_Categories { get; set; }
    }
}
