//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profiling_Participant
    {
        public int Profiling_Participant_Id { get; set; }
        public int Profiling_Instance_Id { get; set; }
        public int Relation_To_Head_Id { get; set; }
        public int Education_Level_Id { get; set; }
        public int Person_Id { get; set; }
        public string Created_By { get; set; }
        public System.DateTime Date_Created { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Date_Last_Modified { get; set; }
    
        public virtual Profiling_Instance NISIS_Profiling_Instance { get; set; }
        public virtual Relationship_Type Relationship_Type { get; set; }
        public virtual Person Person { get; set; }
    }
}
