//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profiling_Tool
    {
        public Profiling_Tool()
        {
            this.NISIS_Profiling_Instances = new HashSet<Profiling_Instance>();
            this.NISIS_Questionnaires = new HashSet<Questionnaire>();
            this.NISIS_Sites = new HashSet<NISIS_Site>();
            this.Community_Profiling_Instances = new HashSet<Community_Profiling_Instance>();
        }
    
        public int Profiling_Tool_Id { get; set; }
        public int Profiling_Tool_Type_Id { get; set; }
        public string Name { get; set; }
        public string Version { get; set; }
        public string Description { get; set; }
        public Nullable<int> Owner_Organization_Id { get; set; }
        public Nullable<int> Contact_Person_id { get; set; }
        public Nullable<System.DateTime> Introduction_Date { get; set; }
        public bool IsDeprecated { get; set; }
        public Nullable<System.DateTime> Deprecation_Date { get; set; }
        public bool Is_Active { get; set; }
        public bool Is_Deleted { get; set; }
        public System.DateTime Date_Created { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Date_Last_Modified { get; set; }
        public string Modified_By { get; set; }
    
        public virtual ICollection<Profiling_Instance> NISIS_Profiling_Instances { get; set; }
        public virtual ICollection<Questionnaire> NISIS_Questionnaires { get; set; }
        public virtual ICollection<NISIS_Site> NISIS_Sites { get; set; }
        public virtual Profiling_Tool_Type NISIS_Profiling_Tool_Type { get; set; }
        public virtual ICollection<Community_Profiling_Instance> Community_Profiling_Instances { get; set; }
    }
}
