//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profiling_Tool_Type
    {
        public Profiling_Tool_Type()
        {
            this.NISIS_Profiling_Tools = new HashSet<Profiling_Tool>();
        }
    
        public int Profiling_Tool_Type_Id { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Profiling_Tool> NISIS_Profiling_Tools { get; set; }
    }
}
