//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Questionnaire_Question_Option
    {
        public int Question_Option_Id { get; set; }
        public int Questionnaire_Question_Id { get; set; }
        public int Option_Id { get; set; }
        public string Option_Text { get; set; }
        public bool Allow_Add_Row { get; set; }
        public bool Is_Active { get; set; }
        public bool Is_Deleted { get; set; }
        public System.DateTime Date_Created { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Date_Last_Modified { get; set; }
        public string Modified_by { get; set; }
    
        public virtual Questionnaire_Question NISIS_Questionnaire_Question { get; set; }
    }
}
