//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Questionnaire_Question
    {
        public Questionnaire_Question()
        {
            this.Profiling_Answers = new HashSet<Profiling_Answer>();
            this.Question_Options = new HashSet<Questionnaire_Question_Option>();
            this.NISIS_Community_Profiling_Answers = new HashSet<Community_Profiling_Answer>();
            this.NISIS_Referral_Engine = new HashSet<NISIS_Referral_Engine>();
            this.Question_Columns = new HashSet<Questionnaire_Question_Column>();
        }
    
        public int Questionnaire_Question_Id { get; set; }
        public int Questionnaire_Section_Id { get; set; }
        public int Sort_Order { get; set; }
        public string Question_Text { get; set; }
        public bool Is_Required { get; set; }
        public bool Is_Active { get; set; }
        public bool Is_Deleted { get; set; }
        public System.DateTime Date_Created { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Date_Last_Modified { get; set; }
        public string Modified_By { get; set; }
        public Nullable<int> Depends_on_Question_Id { get; set; }
        public Nullable<int> Depends_on_Question_Option_Id { get; set; }
    
        public virtual ICollection<Profiling_Answer> Profiling_Answers { get; set; }
        public virtual Questionnaire_Section Questionnaire_Section { get; set; }
        public virtual ICollection<Questionnaire_Question_Option> Question_Options { get; set; }
        public virtual ICollection<Community_Profiling_Answer> NISIS_Community_Profiling_Answers { get; set; }
        public virtual ICollection<NISIS_Referral_Engine> NISIS_Referral_Engine { get; set; }
        public virtual ICollection<Questionnaire_Question_Column> Question_Columns { get; set; }
    }
}
