//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Questionnaire_Question_Column
    {
        public Questionnaire_Question_Column()
        {
            this.NISIS_Question_Validations = new HashSet<NISIS_Question_Validation_Type>();
            this.NISIS_Community_Profiling_Answers = new HashSet<Community_Profiling_Answer>();
            this.NISIS_Profiling_Answers = new HashSet<Profiling_Answer>();
        }
    
        public int Question_Column_Id { get; set; }
        public int Questionnaire_Question_Id { get; set; }
        public int Questionnaire_Question_Type_Id { get; set; }
        public int Column_Id { get; set; }
        public string Column_Heading { get; set; }
        public bool Is_Per_Option { get; set; }
        public bool Is_Active { get; set; }
        public bool Is_Deleted { get; set; }
        public Nullable<int> Populated_From_Question_Id { get; set; }
        public Nullable<int> Populated_From_Question_Column_Id { get; set; }
        public Nullable<int> Populated_By_Type_Id { get; set; }
        public System.DateTime Date_Created { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Date_Last_Modified { get; set; }
        public string Modified_By { get; set; }
    
        public virtual NISIS_Question_Populate_Type NISIS_Question_Populate_Type { get; set; }
        public virtual Questionnaire_Question NISIS_Questionnaire_Question { get; set; }
        public virtual Questionnaire_Question_Type NISIS_Questionnaire_Question_Type { get; set; }
        public virtual ICollection<NISIS_Question_Validation_Type> NISIS_Question_Validations { get; set; }
        public virtual ICollection<Community_Profiling_Answer> NISIS_Community_Profiling_Answers { get; set; }
        public virtual ICollection<Profiling_Answer> NISIS_Profiling_Answers { get; set; }
    }
}
