//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Questionnaire_Section
    {
        public Questionnaire_Section()
        {
            this.Questionnaire_Questions = new HashSet<Questionnaire_Question>();
        }
    
        public int Questionnaire_Section_Id { get; set; }
        public int Questionnaire_Id { get; set; }
        public string Section_Name { get; set; }
        public string Section_Header { get; set; }
        public bool Is_Per_Person { get; set; }
        public int Sort_Order { get; set; }
        public bool Is_Active { get; set; }
        public bool Is_Deleted { get; set; }
        public System.DateTime Date_Created { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Date_Last_Modified { get; set; }
        public string Modified_By { get; set; }
    
        public virtual Questionnaire Questionnaire { get; set; }
        public virtual ICollection<Questionnaire_Question> Questionnaire_Questions { get; set; }
    }
}
