//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Questionnaire_Question_Type
    {
        public Questionnaire_Question_Type()
        {
            this.NISIS_Questionnaire_Question_Column = new HashSet<Questionnaire_Question_Column>();
        }
    
        public int Questionnaire_Question_Type_Id { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Questionnaire_Question_Column> NISIS_Questionnaire_Question_Column { get; set; }
    }
}
