//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RACAP_Correspondence
    {
        public int RACAP_Correspondence_Id { get; set; }
        public Nullable<int> RACAP_Case_Id { get; set; }
        public Nullable<int> RACAP_Correspondence_Type_Id { get; set; }
        public Nullable<System.DateTime> RACAP_Correspondence_Date_Created { get; set; }
        public Nullable<int> RACAP_Correspondence_Created_By { get; set; }
        public Nullable<System.DateTime> RACAP_Correspondence_Date_Modified { get; set; }
        public Nullable<int> RACAP_Correspondence_Modified_By { get; set; }
        public string RACAP_Correspondence_Comments { get; set; }
        public string RACAP_Correspondence_FileName { get; set; }
        public string RACAP_Correspondence_FilePath { get; set; }
    
        public virtual RACAP_Case_Details RACAP_Case_Details { get; set; }
    }
}
