//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RACAP_Case_Details
    {
        public RACAP_Case_Details()
        {
            this.RACAP_Correspondence = new HashSet<RACAP_Correspondence>();
            this.RACAP_OrgansationResponsible = new HashSet<RACAP_OrgansationResponsible>();
            this.RACAP_Prospective_Parent = new HashSet<RACAP_Prospective_Parent>();
            this.RACAP_Removal = new HashSet<RACAP_Removal>();
            this.RACAP_SpecialNeed_Selection = new HashSet<RACAP_SpecialNeed_Selection>();
            this.RACAP_Supporting_Document = new HashSet<RACAP_Supporting_Document>();
        }
    
        public int RACAP_Case_Id { get; set; }
        public Nullable<int> Intake_Assessment_Id { get; set; }
        public Nullable<int> Client_Module_Id { get; set; }
        public Nullable<int> Organization_Id { get; set; }
        public Nullable<System.DateTime> Date_Registered { get; set; }
        public Nullable<int> Adoptions_Reason_Id { get; set; }
        public string Adoption_Surname { get; set; }
        public Nullable<int> RACAP_Record_Status_Id { get; set; }
        public Nullable<System.DateTime> Expiry_Date { get; set; }
        public Nullable<int> RACAP_Registration_Status_Id { get; set; }
        public string Comments { get; set; }
        public Nullable<int> Created_By { get; set; }
        public Nullable<System.DateTime> Date_Created { get; set; }
        public Nullable<int> Modified_By { get; set; }
        public Nullable<System.DateTime> Date_Modified { get; set; }
        public Nullable<System.DateTime> DateCaptured { get; set; }
        public bool Verified { get; set; }
        public Nullable<System.DateTime> DateVerified { get; set; }
        public Nullable<int> VerifiedBy { get; set; }
    
        public virtual Intake_Assessment int_Intake_Assessment { get; set; }
        public virtual ICollection<RACAP_Correspondence> RACAP_Correspondence { get; set; }
        public virtual ICollection<RACAP_OrgansationResponsible> RACAP_OrgansationResponsible { get; set; }
        public virtual ICollection<RACAP_Prospective_Parent> RACAP_Prospective_Parent { get; set; }
        public virtual ICollection<RACAP_Removal> RACAP_Removal { get; set; }
        public virtual ICollection<RACAP_SpecialNeed_Selection> RACAP_SpecialNeed_Selection { get; set; }
        public virtual ICollection<RACAP_Supporting_Document> RACAP_Supporting_Document { get; set; }
    }
}
