//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RACAP_Matches
    {
        public int RACAP_Match_Id { get; set; }
        public Nullable<int> RACAP_Prospective_Parent_Id { get; set; }
        public Nullable<int> RACAP_Adoptive_Child_Id { get; set; }
        public Nullable<System.DateTime> Date_Created { get; set; }
        public Nullable<int> Created_By { get; set; }
        public Nullable<System.DateTime> Date_Modified { get; set; }
        public Nullable<int> Modified_By { get; set; }
    
        public virtual RACAP_Adoptive_Child RACAP_Adoptive_Child { get; set; }
        public virtual RACAP_Prospective_Parent RACAP_Prospective_Parent { get; set; }
    }
}
