//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reception_Visit_Type
    {
        public Reception_Visit_Type()
        {
            this.Reception_Registers = new HashSet<Reception_Register>();
        }
    
        public int Reception_Visit_Type_Id { get; set; }
        public string Description { get; set; }
        public string Source { get; set; }
        public string Definition { get; set; }
    
        public virtual ICollection<Reception_Register> Reception_Registers { get; set; }
    }
}
