//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reception_Register
    {
        public int Reception_Register_Id { get; set; }
        public Nullable<int> Person_Id { get; set; }
        public string Reason_For_Visit { get; set; }
        public Nullable<int> Reception_Visit_Type_Id { get; set; }
        public Nullable<System.DateTime> Visit_Date { get; set; }
        public Nullable<int> Reception_Action_Taken_Id { get; set; }
        public System.DateTime Date_Created { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Date_Last_Modified { get; set; }
        public string Modified_By { get; set; }
        public bool Is_Active { get; set; }
        public bool Is_Deleted { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual Reception_Visit_Type Reception_Visit_Type { get; set; }
        public virtual Reception_Action_Taken Reception_Action_Taken { get; set; }
    }
}
