//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAPS_Official
    {
        public SAPS_Official()
        {
            this.CPR_SAPS_Detail_Items = new HashSet<CPR_SAPS_Detail>();
            this.CPR_SAPS_Investigating_Officer_History = new HashSet<CPR_SAPS_Investigating_Officer_History>();
            this.PCM_Case_Details = new HashSet<PCM_Case_Details>();
        }
    
        public int SAPS_Official_Id { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public Nullable<int> SAPS_Rank_Id { get; set; }
        public string Force_Number { get; set; }
        public string Contact_Number { get; set; }
    
        public virtual ICollection<CPR_SAPS_Detail> CPR_SAPS_Detail_Items { get; set; }
        public virtual SAPS_Rank SAPS_Rank { get; set; }
        public virtual ICollection<CPR_SAPS_Investigating_Officer_History> CPR_SAPS_Investigating_Officer_History { get; set; }
        public virtual ICollection<PCM_Case_Details> PCM_Case_Details { get; set; }
    }
}
