//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAPS_Station
    {
        public SAPS_Station()
        {
            this.CPR_SAPS_Detail = new HashSet<CPR_SAPS_Detail>();
            this.CPR_SAPS_Reported_Police_Station_History = new HashSet<CPR_SAPS_Reported_Police_Station_History>();
            this.PCM_Case_Details = new HashSet<PCM_Case_Details>();
        }
    
        public int SAPS_Station_Id { get; set; }
        public int Town_Id { get; set; }
        public string Description { get; set; }
    
        public virtual Town Town { get; set; }
        public virtual ICollection<CPR_SAPS_Detail> CPR_SAPS_Detail { get; set; }
        public virtual ICollection<CPR_SAPS_Reported_Police_Station_History> CPR_SAPS_Reported_Police_Station_History { get; set; }
        public virtual ICollection<PCM_Case_Details> PCM_Case_Details { get; set; }
    }
}
