//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Section_173_Item
    {
        public Section_173_Item()
        {
            this.CPR_Childrens_Court_Detail = new HashSet<CPR_Childrens_Court_Detail>();
        }
    
        public int Section_173_Item_Id { get; set; }
        public string Description { get; set; }
        public string Source { get; set; }
        public string Definition { get; set; }
    
        public virtual ICollection<CPR_Childrens_Court_Detail> CPR_Childrens_Court_Detail { get; set; }
    }
}
