//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Section_153_Item
    {
        public Section_153_Item()
        {
            this.CPR_Section_153_Items = new HashSet<CPR_Section_153>();
        }
    
        public int Section_153_Item_Id { get; set; }
        public string Description { get; set; }
        public string Tooltip { get; set; }
        public string Source { get; set; }
        public string Definition { get; set; }
    
        public virtual ICollection<CPR_Section_153> CPR_Section_153_Items { get; set; }
    }
}
