//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Treatment_Place
    {
        public Treatment_Place()
        {
            this.Medical_Detail_Items = new HashSet<Medical_Detail>();
        }
    
        public int Treatment_Place_Id { get; set; }
        public string Description { get; set; }
        public string Source { get; set; }
        public string Definition { get; set; }
    
        public virtual ICollection<Medical_Detail> Medical_Detail_Items { get; set; }
    }
}
