//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Role_Delegation
    {
        public int User_Role_Delegation_Id { get; set; }
        public int From_User_Id { get; set; }
        public int To_User_Id { get; set; }
        public System.DateTime Date_From { get; set; }
        public System.DateTime Date_To { get; set; }
    
        public virtual User Delegated_From_User { get; set; }
        public virtual User Delegated_To_User { get; set; }
    }
}
