//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEP_Allocations
    {
        public int Id { get; set; }
        public byte[] Allocated_To { get; set; }
        public byte[] Allocated_By { get; set; }
        public string Allocation_Notes { get; set; }
        public System.DateTime Date_Of_Allocation { get; set; }
    }
}
