//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEP_Sexual_Orientation
    {
        public VEP_Sexual_Orientation()
        {
            this.int_Person = new HashSet<Person>();
        }
    
        public int Sexual_Orientation_Id { get; set; }
        public string Sexual_Orientation { get; set; }
    
        public virtual ICollection<Person> int_Person { get; set; }
    }
}
