//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEP_ServiceType
    {
        public VEP_ServiceType()
        {
            this.VEP_Services = new HashSet<VEP_Services>();
        }
    
        public int ServiceTypeId { get; set; }
        public string ServiceType { get; set; }
    
        public virtual ICollection<VEP_Services> VEP_Services { get; set; }
    }
}
