//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEP_Cases
    {
        public VEP_Cases()
        {
            this.VEP_Services = new HashSet<VEP_Services>();
            this.VEP_VictimsConditions = new HashSet<VEP_VictimsConditions>();
        }
    
        public int CaseId { get; set; }
        public Nullable<int> ClientId { get; set; }
        public string IncidentDetails { get; set; }
        public string PlaceOfIncident { get; set; }
        public Nullable<int> SettlementId { get; set; }
        public Nullable<System.DateTime> DateOfIncident { get; set; }
        public Nullable<System.DateTime> DateOfReporting { get; set; }
        public Nullable<int> KnowPerpetrator { get; set; }
        public Nullable<int> PerpFamilyMemeber { get; set; }
        public Nullable<int> PerpCommunityMember { get; set; }
        public Nullable<int> ReportedToPolice { get; set; }
        public string PoliceCaseNumber { get; set; }
        public string PoliceOBnumber { get; set; }
        public Nullable<int> VictimisationType { get; set; }
        public string VEPReference { get; set; }
        public Nullable<System.DateTime> DateCaptured { get; set; }
        public Nullable<int> SexualOrientationId { get; set; }
    
        public virtual VEP_SettlementType VEP_SettlementType { get; set; }
        public virtual ICollection<VEP_Services> VEP_Services { get; set; }
        public virtual ICollection<VEP_VictimsConditions> VEP_VictimsConditions { get; set; }
    }
}
