//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEP_HomeInformation
    {
        public int Id { get; set; }
        public Nullable<int> ClientId { get; set; }
        public Nullable<int> WhoDoYouStayWithId { get; set; }
        public string NameofHome { get; set; }
        public string NPOnumber { get; set; }
        public string NPOService { get; set; }
    
        public virtual VEP_WhoYouStayWithInfo VEP_WhoYouStayWithInfo { get; set; }
    }
}
