//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEP_VictimsConditions
    {
        public int Id { get; set; }
        public int PresentationConditionID { get; set; }
        public int Caseid { get; set; }
    
        public virtual VEP_Cases VEP_Cases { get; set; }
        public virtual VEP_PresentationCondition VEP_PresentationCondition { get; set; }
    }
}
