//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEP_SettlementType
    {
        public VEP_SettlementType()
        {
            this.VEP_Cases = new HashSet<VEP_Cases>();
        }
    
        public int Id { get; set; }
        public string Settlement { get; set; }
    
        public virtual ICollection<VEP_Cases> VEP_Cases { get; set; }
    }
}
