//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEP_Status
    {
        public VEP_Status()
        {
            this.VEP_Referals = new HashSet<VEP_Referals>();
        }
    
        public int Id { get; set; }
        public string Status { get; set; }
    
        public virtual ICollection<VEP_Referals> VEP_Referals { get; set; }
    }
}
