//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_Objects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEP_Services
    {
        public int ServiceId { get; set; }
        public Nullable<int> PersonId { get; set; }
        public Nullable<int> CaseId { get; set; }
        public Nullable<int> ServiceTypeId { get; set; }
        public string ServiceNotes { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> isActive { get; set; }
    
        public virtual VEP_Cases VEP_Cases { get; set; }
        public virtual VEP_ServiceType VEP_ServiceType { get; set; }
    }
}
